/**
 * The languages this project ships, and the ONE function that turns a stored
 * preference into the language on screen.
 *
 * Every surface resolves here: the web client, the native shells that load
 * the same static export, the server that snapshots a language onto a
 * document, and any surface added later (a browser extension, a CLI). A
 * second copy of this list anywhere is a language one surface accepts and
 * another silently renders in __HATCHKIT_SOURCE_LABEL__.
 *
 * The preference is synced per ACCOUNT; the language is resolved per DEVICE.
 * `resolveLocale("system", …)` answers from the device's own ordered list,
 * and the server passes no list at all — it has no device to ask what
 * "system" means, and guessing from a request header would make the language
 * of a kept document depend on which machine pressed the button. So one
 * account reads __HATCHKIT_TARGET_LABEL__ on a __HATCHKIT_TARGET_LABEL_EN__
 * phone and __HATCHKIT_SOURCE_LABEL__ on a source-language laptop, while an
 * email the server sends falls back to the source language. That asymmetry
 * is the whole reason this module is shared rather than copied per surface.
 *
 * Generated by `hatchkit add i18n`. Adding a language by hand means one entry
 * in SUPPORTED_LOCALES, one row in each table below, and one catalog file per
 * namespace — `tsc` names every one of them.
 */

/** The language the source catalogs are written in, and the answer whenever
 *  nothing else applies. Annotated rather than inferred on purpose: the
 *  annotation fails the build if the source locale is ever missing from
 *  SUPPORTED_LOCALES, which would leave the fallback pointing at nothing. */
export const SOURCE_LOCALE: SupportedLocale = "__HATCHKIT_SOURCE_LOCALE__";

/** Every locale with a complete catalog. Source first: this order is the
 *  fallback order, and the prerendered HTML is in the source language. */
export const SUPPORTED_LOCALES = __HATCHKIT_ALL_LOCALES_JSON__ as const;

export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

/** What a person picks in settings. "system" is not a language — it is a
 *  deferral to whatever device they happen to be reading on. */
export type LocalePreference = "system" | SupportedLocale;

/** Endonyms — what each language calls itself. A picker must show these:
 *  a reader who cannot read the current UI language still recognises their
 *  own. `Intl.DisplayNames` is deliberately not used; it answers in the
 *  CURRENT language ("German" while the UI is English), which is exactly the
 *  wrong string for the one control a lost reader needs. */
const KNOWN_ENDONYMS: Readonly<Record<string, string>> = {
  en: "English",
  de: "Deutsch",
  fr: "Français",
  es: "Español",
  it: "Italiano",
  pt: "Português",
  nl: "Nederlands",
  pl: "Polski",
  sv: "Svenska",
  da: "Dansk",
  ja: "日本語",
  zh: "中文",
};

/** Default Intl region per language, used only when the device offers none.
 *  There is no "the region for de" in CLDR — this is an editorial pick, and
 *  a de-AT device overrides it and keeps „Jänner“. */
const KNOWN_REGIONS: Readonly<Record<string, string>> = {
  en: "US",
  de: "DE",
  fr: "FR",
  es: "ES",
  it: "IT",
  pt: "PT",
  nl: "NL",
  pl: "PL",
  sv: "SE",
  da: "DK",
  ja: "JP",
  zh: "CN",
};

/** Project the tables above onto this project's own locale set, so both
 *  records are TOTAL whatever the set is. A hand-added language that forgot
 *  its row still shows its code in the picker and still formats against a
 *  plausible region, instead of rendering `undefined` into a page. */
function localeTable(
  known: Readonly<Record<string, string>>,
  fallback: (locale: SupportedLocale) => string,
): Record<SupportedLocale, string> {
  const table = {} as Record<SupportedLocale, string>;
  for (const locale of SUPPORTED_LOCALES) table[locale] = known[locale] ?? fallback(locale);
  return table;
}

export const LOCALE_ENDONYMS: Record<SupportedLocale, string> = localeTable(
  KNOWN_ENDONYMS,
  (locale) => locale,
);

export const LOCALE_REGIONS: Record<SupportedLocale, string> = localeTable(
  KNOWN_REGIONS,
  (locale) => locale.toUpperCase(),
);

export function isSupportedLocale(value: unknown): value is SupportedLocale {
  return typeof value === "string" && (SUPPORTED_LOCALES as readonly string[]).includes(value);
}

/**
 * The first supported language in an ordered preference list
 * (`navigator.languages`, or a parsed `Accept-Language`).
 *
 * Matching is by PRIMARY SUBTAG only: "de-AT", "de_CH" and "de;q=0.8" all
 * read __HATCHKIT_TARGET_LABEL__, because the catalogs are per language and
 * not per region. A browser set to "fr, de, en" reads German when French is
 * unavailable — the order is the reader's own ranking, so the first hit wins
 * rather than the best-known one.
 */
export function matchLocaleList(list: readonly string[] | undefined | null): SupportedLocale {
  for (const tag of list ?? []) {
    const primary = tag.trim().toLowerCase().split(/[-_;]/)[0] ?? "";
    if (isSupportedLocale(primary)) return primary;
  }
  return SOURCE_LOCALE;
}

/**
 * A stored preference plus the device's languages → the language to render.
 *
 * "system" defers to `deviceList`. Pass no list and the answer is always
 * SOURCE_LOCALE: that is the server's call shape, and it is correct rather
 * than lazy — the server has no device, so it must not resolve "system" at
 * all. Callers that accept `null` from a database row are the reason the
 * preference is nullable here.
 */
export function resolveLocale(
  pref: LocalePreference | undefined | null,
  deviceList?: readonly string[],
): SupportedLocale {
  if (pref !== undefined && pref !== null && pref !== "system" && isSupportedLocale(pref)) {
    return pref;
  }
  return matchLocaleList(deviceList);
}

/**
 * The Intl tag to format with: the RENDERED language plus the DEVICE's
 * region. A reader on en-GB keeps "21 Aug" while reading English, and a
 * reader on de-AT keeps „Jänner“ while reading German — the language comes
 * from the preference, the conventions come from the machine in their hand.
 * An unusable region falls back to this language's default.
 */
export function intlTag(locale: SupportedLocale, region?: string): string {
  const candidate = region?.trim().toUpperCase();
  const usable = candidate !== undefined && /^(?:[A-Z]{2}|[0-9]{3})$/.test(candidate);
  return `${locale}-${usable ? candidate : LOCALE_REGIONS[locale]}`;
}

/**
 * "Same keys, same shape as the source catalog" — the type every translation
 * file is annotated with.
 *
 * Exact on purpose: no index signature and no optional keys, so a missing
 * key, a misspelled key and a key that no longer exists are each a `tsc`
 * error in the translation file rather than a `namespace.key` string on a
 * page nobody on the team can read. What it CANNOT see is inside the string:
 * a renamed ICU placeholder type-checks and renders raw braces, which is
 * what `catalog-parity.test.ts` is for.
 */
export type Translation<T> = {
  [K in keyof T]: T[K] extends string ? string : Translation<T[K]>;
};
