/*
 * cli/src/features/release/docs.ts — the two generated Markdown
 * documents of the `release` feature: `docs/releasing.md` (the
 * procedure) and `docs/release-credentials.md` (the secrets).
 *
 * WHY THESE ARE GENERATED RATHER THAN WRITTEN
 * -------------------------------------------
 * A hand-written release doc describes the channels a project had on
 * the day somebody wrote it. Add a store six months later and the doc is
 * wrong in the one place people trust it: what the tag will do. Both
 * documents here are a projection of the {@link ReleaseConfig}, so they
 * name the channels the project has and nothing else. A project with one
 * web deploy gets a short true page, not a long page about stores it
 * does not ship to.
 *
 * Both renderers are pure functions of the config — no disk, no
 * network, no clock. That is what lets the tests assert on the text for
 * any config shape, including the empty one, and it is why every
 * "degrades cleanly" branch below is reachable in a unit test.
 *
 * House style for the prose: one idea per sentence, active voice, and
 * every claim checkable in the generated project. When a fact is not in
 * the config, these documents do not invent it.
 */

import {
  type AbsentBehaviour,
  type ChannelGate,
  type CredentialGroup,
  type PolicyRule,
  RELEASE_CONFIG_FILENAME,
  type ReleaseChannel,
  type ReleaseConfig,
} from "./types.js";

// ---------------------------------------------------------------------------
// Small shared helpers
// ---------------------------------------------------------------------------

/** A Markdown code span. Written as concatenation because these files
 *  build their output from ordinary string literals, not template
 *  literals — backticks and `${` both appear in the output verbatim. */
const code = (value: string): string => "`" + value + "`";

/** Makes a value safe inside a Markdown table cell. A pipe would end
 *  the cell and a newline would end the row; both appear in
 *  hand-written `note` and `what` strings. */
const cell = (value: string): string => value.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");

/** Joins a list into English: "a", "a and b", "a, b and c". */
function sentenceList(items: readonly string[]): string {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0];
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

/** How this project invokes one of its own package scripts. npm always
 *  needs `run`, and needs `--` before arguments of its own; pnpm and yarn
 *  take the script name directly and pass arguments through. */
function scriptCommand(
  packageManager: ReleaseConfig["project"]["packageManager"],
  script: string,
  args = "",
): string {
  if (packageManager === "npm") {
    return args === "" ? `npm run ${script}` : `npm run ${script} -- ${args}`;
  }
  return args === "" ? `${packageManager} ${script}` : `${packageManager} ${script} ${args}`;
}

/** Joins the collected lines into a finished document: no run of blank
 *  lines longer than one, and exactly one trailing newline. The section
 *  builders below push a blank after every block whether or not the next
 *  block arrives, which is what keeps each of them independent. */
function markdownFile(lines: readonly string[]): string {
  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** The notice both documents open with. Placed directly under the title
 *  so it is the first thing a reader meets, in the rendered page and in
 *  the raw file alike — whichever one they are about to edit. */
function generatedNotice(): string {
  return (
    `_Generated by ${code("hatchkit update")} from ${code(RELEASE_CONFIG_FILENAME)}. ` +
    "Edits to this file are lost on the next run. Change the project, then run " +
    `${code("hatchkit update")} again._`
  );
}

/** One sentence naming the consequence of a missing credential set. The
 *  wording is fixed per behaviour so the same absence always reads the
 *  same way, wherever it is reported. */
function absentSentence(absent: AbsentBehaviour): string {
  switch (absent) {
    case "skip":
      return "The upload step does not run. The build still runs, and its output stays attached to the workflow run.";
    case "unsigned":
      return "The artifact is built without a signature. It is not uploaded anywhere a person could install it from.";
    case "fail":
      return "The workflow fails. This channel cannot degrade.";
  }
}

/** The same fact in a table cell, where the row already carries the
 *  channel name. */
function absentCell(absent: AbsentBehaviour): string {
  switch (absent) {
    case "skip":
      return "Upload skipped; the build is still attached to the run";
    case "unsigned":
      return "Built unsigned and not uploaded";
    case "fail":
      return "The workflow fails";
  }
}

/** What a person still owes after the workflow turns green. */
function gateCell(gate: ChannelGate | null): string {
  return gate === null ? "Nothing" : cell(gate.note);
}

/** What the tag starts, for the channel table. Two channels never have a
 *  run for the tag, for different reasons, and a reader who does not
 *  know which one they are looking at waits for a run that was never
 *  going to arrive. */
function tagEffectCell(channel: ReleaseChannel): string {
  if (channel.trigger === "branch") {
    return `Nothing — this workflow runs on a push to the default branch, not on a tag. ${cell(channel.effect)}`;
  }
  if (channel.trigger === "tag-dispatch") {
    return `Nothing until you dispatch it from the tag, in Actions → ${cell(channel.workflowName)}. ${cell(channel.effect)}`;
  }
  return cell(channel.effect);
}

// ---------------------------------------------------------------------------
// Policy rules, in prose
// ---------------------------------------------------------------------------

/** What a rule refuses, and why that refusal is worth having. Derived
 *  from the rule's `kind` so a new rule kind cannot ship undocumented:
 *  the compiler reports the missing branch. */
function policyRuleProse(
  rule: PolicyRule,
  config: ReleaseConfig,
): { refuses: string; why: string } {
  const versionFile = code(config.project.versionFile);
  switch (rule.kind) {
    case "version-matches-tag":
      return {
        refuses: `a tag whose number differs from the version in ${versionFile}`,
        why: "The tag names the release. A mismatch ships a build under a number nobody can look up.",
      };
    case "version-copies-match":
      return {
        refuses: `a release where a copy of the version disagrees with ${versionFile}`,
        why: "One stale copy ships the previous number to that one surface, and only that surface.",
      };
    case "no-prerelease-to-public": {
      const names = rule.channels.map((id) => channelLabel(config, id));
      return {
        refuses: `a prerelease tag while ${sentenceList(names)} distribute publicly`,
        why: "People who did not ask for a prerelease would be given one.",
      };
    }
    case "credential-set-complete":
      return {
        refuses: `a half-set of the ${channelLabel(config, rule.channelId)} credentials (${rule.secrets.map(code).join(", ")})`,
        why: "Half a set builds the artifact and then uploads nothing, or uploads it unsigned.",
      };
    case "no-unsigned-publish":
      return {
        refuses: `publishing ${channelLabel(config, rule.channelId)} while ${sentenceList(rule.signingSecrets.map(code))} ${rule.signingSecrets.length === 1 ? "is" : "are"} absent`,
        why: "An unsigned build must not reach a person who can install it.",
      };
    case "tag-is-new":
      return {
        refuses: "a tag that is not newer than the newest release tag that already exists",
        why: "Version numbers only go forward. Every reader that compares them assumes that.",
      };
    case "release-record":
      return {
        refuses: `a release with no heading for this version in ${code(rule.path)}`,
        why: "Somebody deciding whether to upgrade has to be able to read what changed.",
      };
  }
}

/** A channel id turned into its label, or the raw id when the channel is
 *  gone. An unknown id is a derivation bug, so the doc prints it rather
 *  than hiding it. */
function channelLabel(config: ReleaseConfig, channelId: string): string {
  return config.channels.find((channel) => channel.id === channelId)?.label ?? channelId;
}

// ---------------------------------------------------------------------------
// docs/releasing.md
// ---------------------------------------------------------------------------

/**
 * The procedure: how to cut a release, what each channel does on the
 * tag, what a person still owes afterwards, and how to read the status
 * table.
 */
export function renderReleasingDoc(config: ReleaseConfig): string {
  const { project, channels, policy, compat } = config;
  const pm = project.packageManager;
  const cut = scriptCommand(pm, "release", "X.Y.Z");
  const cutDry = scriptCommand(pm, "release", "X.Y.Z --dry-run");
  const status = scriptCommand(pm, "release:status");
  const exampleTag = `${project.tagPrefix}X.Y.Z`;

  const out: string[] = [];
  out.push(`# Releasing ${project.name}`, "", generatedNotice(), "");

  out.push(
    `A release is one git tag, ${code(exampleTag)}. ${code(cut)} cuts it and pushes nothing.`,
  );
  if (channels.length > 0) {
    out.push(
      `Pushing the tag starts the channel workflows below. ${code(status)} then tells you what each one did.`,
    );
  }
  out.push("");

  // -- Channels -----------------------------------------------------------
  out.push("## What the tag ships", "");
  if (channels.length === 0) {
    out.push(
      "This project has no release channels yet. A tag records the version and starts nothing.",
      `Enable a surface, run ${code("hatchkit update")}, and its channel appears here.`,
      "",
    );
  } else {
    out.push("| Channel | Workflow | What the tag does | What you still do |");
    out.push("|---|---|---|---|");
    for (const channel of channels) {
      out.push(
        `| ${cell(channel.label)} | ${code(channel.workflowFile)} | ${tagEffectCell(channel)} | ${gateCell(channel.gate)} |`,
      );
    }
    out.push("");
    const gated = channels.filter((channel) => channel.gate !== null);
    if (gated.length > 0) {
      out.push(
        `A green workflow is not yet a release for ${sentenceList(gated.map((channel) => channel.label))}. ` +
          "Each one needs the step in the last column before anybody has the new version.",
        "",
      );
    }
  }

  // -- Version copies -----------------------------------------------------
  out.push("## Where the version is written", "");
  out.push(
    config.versionCopies.length === 0
      ? `${code(project.versionFile)} holds the one version, and nothing else keeps a copy of it. The cut command sets it.`
      : `${code(project.versionFile)} holds the one version. The cut command sets it, and sets every copy below to the same value.`,
    "",
  );
  if (config.versionCopies.length > 0) {
    out.push("| File | Copy |");
    out.push("|---|---|");
    for (const copy of config.versionCopies) {
      out.push(`| ${code(copy.path)} | ${cell(copy.label)} |`);
    }
    out.push("");
    out.push(
      "The generated version-sync test asserts each of these. It fails until they agree, which is before anything is uploaded.",
      "",
    );
  }
  if (config.versionReads.length > 0) {
    out.push(
      `These read the version at build time instead of keeping a copy: ${sentenceList(config.versionReads.map((read) => read.label))}.`,
      "The same test pins that, so a later refactor cannot turn a build-time read back into a literal.",
      "",
    );
  }

  // -- Steps --------------------------------------------------------------
  out.push("## Cutting a release", "");
  const record = policy.rules.find(
    (rule): rule is Extract<PolicyRule, { kind: "release-record" }> =>
      rule.kind === "release-record",
  );
  let step = 1;

  if (record !== undefined) {
    out.push(
      `${step}. **Write the record.** ${code(record.path)} needs a heading for this version and a description of what changed.`,
      "   The policy check refuses the tag without it.",
      "",
    );
    step += 1;
  }

  out.push(
    `${step}. **Cut the tag.**`,
    "",
    "   ```bash",
    `   ${cutDry}`,
    `   ${cut}`,
    "   ```",
    "",
    `   The dry run prints the plan and writes nothing. The real run sets the version, runs the policy check,`,
    project.testCommand === null
      ? "   then commits and creates the annotated tag. It pushes nothing."
      : `   runs ${code(project.testCommand)}, then commits and creates the annotated tag. It pushes nothing.`,
    "",
  );
  step += 1;

  out.push(
    `${step}. **Push the branch, then the tag.**`,
    "",
    "   ```bash",
    "   git push origin main",
    `   git push origin ${exampleTag}`,
    "   ```",
    "",
    "   The workflows build what GitHub has, not your local checkout. Push the commit first.",
    "",
  );
  step += 1;

  out.push(
    `${step}. **Read the result.** Run ${code(status)}, or open the newest Release Summary run for the tag on GitHub.`,
    "",
  );
  step += 1;

  const gates = channels.filter(
    (channel): channel is ReleaseChannel & { gate: ChannelGate } => channel.gate !== null,
  );
  if (gates.length > 0) {
    out.push(`${step}. **Finish what the workflows cannot.**`, "");
    for (const channel of gates) {
      out.push(`   - ${channel.label}: ${channel.gate.note}`);
    }
    out.push("");
  }

  // -- Policy -------------------------------------------------------------
  out.push("## What the policy check refuses", "");
  if (policy.rules.length === 0) {
    out.push("This project has no policy rules. Nothing blocks a tag.", "");
  } else {
    out.push(
      `${code("node scripts/release-policy-check.mjs " + exampleTag)} runs these rules. The cut command runs the same check before it writes a file,`,
      "and the release workflow runs it again on the tagged commit.",
      "",
    );
    for (const rule of policy.rules) {
      const prose = policyRuleProse(rule, config);
      const blocking = policy.warnOnly.includes(rule.id)
        ? "_Reported; does not block._"
        : "_Blocks the release._";
      out.push(`- **${code(rule.id)}** — refuses ${prose.refuses}. ${prose.why} ${blocking}`);
    }
    out.push("");
  }

  // -- Status table -------------------------------------------------------
  out.push("## Reading the status table", "");
  out.push(
    `${code(status)} reads the newest run of each channel workflow for the tag, through ${code("gh api")} only. It changes nothing.`,
    "Each row is one channel: its label, its workflow, the run's result as a link, and the facts the run produced.",
    "",
  );
  if (channels.some((channel) => channel.uploadSteps.length > 0)) {
    out.push(
      "The facts come from named steps inside the run. A renamed step turns its fact into `unknown` rather than into a wrong answer.",
      "",
    );
  }
  const missing = channels.filter((channel) => channel.missingRunNote !== null);
  if (missing.length > 0) {
    out.push("A missing run is expected for these:", "");
    for (const channel of missing) {
      out.push(`- ${channel.label}: ${channel.missingRunNote}`);
    }
    out.push("");
  }
  out.push(
    "On GitHub the same table is the step summary of the newest `Release Summary` run for the tag.",
    "Each channel workflow finishing starts a fresh one, so the last summary is the whole picture.",
    "",
  );
  if (channels.some((channel) => channel.gate?.kind === "draft-release")) {
    out.push(
      "That summary runs with a read-only token, and GitHub shows draft releases to write access only.",
      `It reports no release for the tag until you publish the draft. Run ${code(status)} locally for that one fact.`,
      "",
    );
  }

  // -- Compat -------------------------------------------------------------
  if (compat !== null) {
    out.push("## Cross-version compatibility", "");
    out.push(
      "`.github/workflows/compat.yml` runs on every pull request to `main`, in both directions, against the previous stable tag:",
      "",
      "- **New client, old server.** This checkout's suite against the previous release's server image.",
      "- **Old client, new server.** The previous release's suite against a server image built from this checkout.",
      "",
      "Self-hosted servers lag and store clients lead, so old and new meet in the field either way.",
      "This is the mechanical check that the minimum levels each release declares are honest.",
      "",
      "Each direction skips with a notice, never a failure: the first while no release tag exists,",
      `the second while no tag contains ${code(compat.suiteEntry)} yet.`,
      "",
      "A refusal the suite makes on purpose, because a peer is below the declared minimum, is the expected answer.",
      "Any other refusal fails the job. Raise the declared minimum, or fix the change that broke the peer.",
      "",
    );
  }

  // -- Provenance ---------------------------------------------------------
  out.push("## Where this comes from", "");
  out.push(
    `${code(RELEASE_CONFIG_FILENAME)} lists the channels, the version copies, the credential groups and the policy rules.`,
    "`scripts/release.mjs`, `scripts/release-status.mjs` and `scripts/release-policy-check.mjs` read it and hold no knowledge of any one channel.",
    `Change the project, run ${code("hatchkit update")}, and this page changes with it.`,
    "",
  );

  return markdownFile(out);
}

// ---------------------------------------------------------------------------
// docs/release-credentials.md
// ---------------------------------------------------------------------------

/**
 * The secrets: what each channel needs, where each value comes from,
 * what happens without it, and the one-time steps a vendor forces
 * through a UI.
 *
 * Names only. A value never reaches this file, because the file is
 * committed.
 */
export function renderCredentialsDoc(config: ReleaseConfig): string {
  const out: string[] = [];
  out.push(`# Release credentials — ${config.project.name}`, "", generatedNotice(), "");

  if (config.credentials.length === 0) {
    out.push(...noCredentialsBody(config));
    return markdownFile(out);
  }

  out.push(
    "Every channel of this project, and what it does when its credentials are absent.",
    "No value belongs in this file: it holds secret **names** only, and it is committed.",
    "",
  );

  // -- The whole picture, one table ---------------------------------------
  const groupByChannel = new Map<string, CredentialGroup>();
  for (const group of config.credentials) groupByChannel.set(group.channelId, group);

  out.push("| Channel | Secrets | When they are absent |");
  out.push("|---|---|---|");
  for (const channel of config.channels) {
    const group = groupByChannel.get(channel.id);
    const secrets = group?.secrets.map((secret) => secret.name) ?? channel.credentials;
    if (secrets.length === 0) {
      out.push(`| ${cell(channel.label)} | none | Publishes with the workflow's own token |`);
      continue;
    }
    out.push(
      `| ${cell(channel.label)} | ${secrets.map(code).join(", ")} | ${absentCell(group?.absent ?? channel.absent)} |`,
    );
  }
  // A group whose channel is gone is a derivation bug. Print it rather
  // than dropping a credential requirement on the floor.
  for (const group of config.credentials) {
    if (config.channels.some((channel) => channel.id === group.channelId)) continue;
    out.push(
      `| ${cell(group.label)} | ${group.secrets.map((secret) => code(secret.name)).join(", ")} | ${absentCell(group.absent)} |`,
    );
  }
  out.push("");

  out.push(
    `Set one with ${code("gh secret set <NAME>")} from the repository, or in Settings → Secrets and variables → Actions.`,
    "",
  );

  // -- One section per group ----------------------------------------------
  for (const group of config.credentials) {
    out.push(`## ${group.label}`, "");
    out.push("| Secret | What it is | Where it comes from |");
    out.push("|---|---|---|");
    for (const secret of group.secrets) {
      out.push(`| ${code(secret.name)} | ${cell(secret.what)} | ${cell(secret.where)} |`);
    }
    out.push("");

    out.push("**When these are absent.**", "");
    out.push(`${absentSentence(group.absent)} ${group.absentNote}`, "");

    if (group.manualSteps.length > 0) {
      out.push(
        "**One-time setup.** These cannot be automated; the vendor forces each one through its own UI.",
        "",
      );
      group.manualSteps.forEach((manualStep, index) => out.push(`${index + 1}. ${manualStep}`));
      out.push("");
    }
  }

  const halfSetRules = config.policy.rules.filter(
    (rule): rule is Extract<PolicyRule, { kind: "credential-set-complete" }> =>
      rule.kind === "credential-set-complete",
  );
  if (halfSetRules.length > 0) {
    const guarded = sentenceList(halfSetRules.map((rule) => channelLabel(config, rule.channelId)));
    out.push("## Half a set is refused", "");
    out.push(
      `The policy check refuses a release where the credentials of ${guarded} are partly set.`,
      "Half a set is the shape that builds an artifact and then uploads nothing, or uploads it unsigned.",
      "Set all of a group, or none of it.",
      "",
    );
  }

  return markdownFile(out);
}

/** The honest short version, for a project whose channels need nothing
 *  beyond the workflow's own token. An empty skeleton of headings would
 *  read as a document somebody forgot to finish. */
function noCredentialsBody(config: ReleaseConfig): string[] {
  if (config.channels.length === 0) {
    return [
      "This project has no release channels yet, so there is no credential to set.",
      `Enable a surface and run ${code("hatchkit update")}. A channel that needs a secret gets a section here.`,
      "",
    ];
  }
  const labels = sentenceList(config.channels.map((channel) => channel.label));
  return [
    `No channel of this project needs a credential. The workflow's own ${code("GITHUB_TOKEN")} covers ${labels}.`,
    "There is nothing to set in Settings → Secrets and variables → Actions, and nothing to rotate.",
    `Enable a surface that publishes elsewhere, run ${code("hatchkit update")}, and its secrets get a section here.`,
    "",
  ];
}
