/*
 * The written form of the topology facts — one document for a person
 * reading a broken deploy, and one compact section for the agent memory
 * file of the project itself.
 *
 * ---------------------------------------------------------------------
 * Why generate this at all
 * ---------------------------------------------------------------------
 *
 * The four facts in ./advice.ts are checkable, and `hatchkit doctor`
 * checks them. But the checks only fire against a manifest hatchkit can
 * see. The failures themselves show up as four symptoms with no obvious
 * cause — a 404 from a host that resolves, a gateway error from an
 * application the dashboard calls healthy, a TLS handshake that fails
 * before any request exists — and the person reading them is usually
 * not the person who chose the topology. Every one of those symptoms
 * has exactly one cause, and the table below is the shortest path from
 * one to the other.
 *
 * The CLAUDE.md section exists for the same reason one level up: the
 * next agent to touch a project reads that file first, and "simplify
 * this to one application" or "serve the API from a path" are both
 * plausible-looking changes that re-create a solved outage. The section
 * states the reason, not the rule, because a rule without its reason is
 * the thing an agent optimizes away.
 *
 * ---------------------------------------------------------------------
 * Rules every transform here follows
 * ---------------------------------------------------------------------
 *
 *   1. The project's own hostnames, never an example. A document
 *      carrying someone else's domain is a document nobody checks their
 *      own values against.
 *   2. The CLAUDE.md retrofit is idempotent and anchored. It replaces
 *      what is between its markers, and when it cannot find a sane
 *      insertion point it returns the file UNCHANGED — a hand-written
 *      memory file is safer left alone than half-rewritten.
 */

import type { OperationalProject } from "../operational-context.js";
import {
  defaultApiOrigin,
  defaultWebOrigin,
  hasClientHalf,
  hasServerHalf,
} from "../operational-context.js";
import {
  inferZone,
  normalizeHost,
  recommendedDomainLayout,
  splitApiHost,
  wildcardAlternatives,
} from "./advice.js";

/** Where the generated document lands, relative to the project root. */
export const TOPOLOGY_DOC_REL = "docs/deploy-topology.md";

/** The first line of the generated document.
 *
 *  `writeIfChanged` overwrites, which is the right primitive for a file
 *  hatchkit regenerates from the manifest — and the wrong surprise for
 *  somebody who edited it. An owned file has to say it is owned, in the
 *  file, because that is the only place the person about to edit it is
 *  looking. */
export const OWNED_FILE_NOTICE =
  "<!-- Generated by hatchkit from .hatchkit.json. Rewritten on every `hatchkit update` — put your own notes in another file. -->";

/** Markers around the CLAUDE.md section. Stable strings: they are the
 *  only thing that makes a second run an update instead of a duplicate,
 *  so changing them orphans every section already written. */
/* The managed-section anchors.
 *
 * `hatchkit-managed:`, deliberately NOT `hatchkit:`. The `hatchkit:`
 * namespace belongs to the starter's own conditional-pruning syntax
 * (`hatchkit:if` / `hatchkit:endif`, see scaffold/claude-md.ts), which
 * is template machinery that must never survive into a generated
 * project — test-scaffold.ts asserts a scaffolded CLAUDE.md contains no
 * `hatchkit:` at all, and that assertion is worth keeping literally,
 * because anything matching it IS residue.
 *
 * These two are the opposite kind of marker: they are meant to survive,
 * so that a later `hatchkit update` can replace the section between
 * them instead of appending a second copy. A separate namespace keeps a
 * reader from mistaking one for the other.
 *
 * This is also why the section is NOT maintained with the ledger's
 * `ensureManagedBlock`, which is otherwise exactly the right primitive
 * for a region of a file the user also edits. That helper owns its own
 * marker syntax, and for CLAUDE.md it would emit two things this file
 * cannot have:
 *
 *   · `hatchkit:begin topology-guidance` — which the scaffold test
 *     reads as template residue and fails on.
 *   · a `#` comment prefix, because `inferCommentPrefix` has no rule
 *     for Markdown and falls back to it — so each marker would render
 *     as a top-level heading in the middle of the memory file.
 *
 * So the block stays hand-rolled, and {@link upsertClaudeMdSection} is
 * handed to `ledger.edit` as a fixed-point transform instead. It gets
 * the same two guarantees (replace in place, never duplicate) with an
 * HTML comment a Markdown reader does not see. */
export const CLAUDE_MD_BEGIN = "<!-- hatchkit-managed:topology-guidance -->";
export const CLAUDE_MD_END = "<!-- hatchkit-managed:end-topology-guidance -->";

/** Headings under which the section is a sane fit when no markers exist
 *  yet. Anything else is left alone — see rule 2 in the module header. */
const ANCHOR_HEADING = /^(#{2,4})\s+.*\b(deploy|deployment|hosting|infrastructure|production)\b/i;

interface Hosts {
  /** Hostname the site is served from, or "" when there is no site. */
  web: string;
  /** Hostname the API is served from, or "" when there is no API. */
  api: string;
  /** Origin the clients are built against. */
  apiOrigin: string;
  webOrigin: string;
  zone: string;
  split: boolean;
}

/** Resolve the hostnames a project actually has, so every sentence in
 *  the generated text can name one instead of describing one. */
function hostsOf(project: OperationalProject): Hosts {
  const domain = normalizeHost(project.domain);
  const split = project.topology === "split";
  const server = hasServerHalf(project.surfaces);
  const client = hasClientHalf(project.surfaces);
  const apiHost = split && client ? splitApiHost(domain) : domain;
  return {
    web: client ? domain : "",
    api: server ? apiHost : "",
    apiOrigin: defaultApiOrigin(domain, project.topology),
    webOrigin: defaultWebOrigin(domain),
    zone: inferZone(domain),
    split,
  };
}

// ---------------------------------------------------------------------------
// The full document
// ---------------------------------------------------------------------------

/** Render `docs/deploy-topology.md` for one project: the four facts,
 *  the symptom table, the one-time platform setup and the verification
 *  commands, all carrying that project's own hosts.
 *
 *  Rendered for single-origin projects too, with the facts stated as
 *  the constraints a later split will meet. A project that has not
 *  split yet is exactly the project about to walk into them. */
export function renderTopologyDoc(project: OperationalProject): string {
  const h = hostsOf(project);
  const layout = recommendedDomainLayout({
    domain: project.domain,
    topology: project.topology,
    surfaces: project.surfaces,
  });
  const lines: string[] = [];

  // The document is owned by hatchkit and rewritten whole on every run,
  // so it has to say so: a reader who edits it here loses the edit on
  // the next `hatchkit update`, and the only way to find that out
  // otherwise is to lose one.
  lines.push(OWNED_FILE_NOTICE);
  lines.push("");
  lines.push(`# Deploying ${project.name}`);
  lines.push("");
  lines.push(
    h.split
      ? `Two applications on two hosts of the \`${h.zone}\` zone. Each one deploys, restarts and fails on its own.`
      : `One application on \`${h.web || h.api}\`, serving every half of the project from a single origin.`,
  );
  lines.push("");
  lines.push("| Application | Serves | Routed at |");
  lines.push("| --- | --- | --- |");
  for (const app of layout.apps) {
    const appName = h.split ? `\`${project.name}-${app.role}\`` : `\`${project.name}\``;
    lines.push(
      `| ${appName} | ${app.serves} | ${app.hosts.map((x) => `\`https://${x}\``).join(", ")} |`,
    );
  }
  lines.push("");

  lines.push("## 1. Two applications, not one");
  lines.push("");
  lines.push(
    "The unit of deployment is the application. Everything inside one restarts together, so one application holding both halves means a change to the browser bundle restarts the API with it.",
  );
  lines.push("");
  lines.push(
    "That drops every connection the server was holding — open sockets, in-flight uploads, live subscriptions — for a change that never touched the server. Two applications restart independently, which is the whole reason for the split.",
  );
  if (!h.split) {
    lines.push("");
    lines.push(
      `This project runs **one** application today. A deploy of the site restarts the API. Split it when the server starts holding connections that a site deploy must not break.`,
    );
  }
  lines.push("");

  lines.push("## 2. The service name inside each compose file is load-bearing");
  lines.push("");
  lines.push(
    "The platform keys its domain routing by compose service name. It does not validate the key against the compose file.",
  );
  lines.push("");
  lines.push(
    "A key naming a service that is not declared is accepted by the API with a success response, emits no proxy labels at all, and leaves the site answering a gateway error. **A 200 from the API and a broken site is the signature of this bug** — nothing in the dashboard reports it, because as far as the platform is concerned the write succeeded.",
  );
  lines.push("");
  if (h.split) {
    lines.push(
      "So the service names in `docker-compose.client.yml` and `docker-compose.server.yml` (`client` and `server`) must stay exactly as they are. Renaming a service without changing the routing entry is a silent outage.",
    );
  } else {
    lines.push(
      "So the service names in `docker-compose.yml` must match the routing entries exactly. Renaming a service without changing the routing entry is a silent outage.",
    );
  }
  lines.push("");

  lines.push("## 3. The split is by host, never by path");
  lines.push("");
  lines.push(
    "Serving the API from a path on the site's host looks like the cheaper answer: one hostname, one DNS record, one certificate, and the browser stays same-origin. It does not work, for two independent reasons, and either one is fatal.",
  );
  lines.push("");
  lines.push(
    "**The proxy merges site blocks for the same host.** Two applications on one host both write the same site. The merge keeps one of them, and the winner swallows the other's traffic — so a request for the API is answered by the site's own 404 page. There is no more-specific-rule-wins ordering to rely on here.",
  );
  lines.push("");
  lines.push(
    "**The matched path prefix is stripped.** Even with the order forced, a route matched on `/api` delivers the request with `/api` removed. The API mounts its own routes *at* `/api`, so it receives `/trpc` where it expects `/api/trpc` and answers 404 to everything.",
  );
  lines.push("");
  lines.push(
    "Each application therefore needs a host of its own, and each host routes at `/`, where nothing is stripped. **Never put a path in an application's domain field.**",
  );
  lines.push("");

  lines.push("## 4. A host of its own needs a certificate that covers it");
  lines.push("");
  lines.push(
    `A wildcard certificate covers exactly ONE label below its zone: a certificate for \`${h.zone}\` covers \`${h.zone}\` and \`*.${h.zone}\`, and nothing deeper.`,
  );
  lines.push("");
  lines.push(
    "A host two labels below the zone fails the TLS handshake before any HTTP happens. No routing check tells you anything useful behind that, because no request is ever made:",
  );
  lines.push("");
  lines.push("```");
  lines.push("curl: (35) error:0A000410:SSL routines::sslv3 alert handshake failure");
  lines.push("```");
  lines.push("");
  if (h.api) {
    const depthNote = layout.wildcardTrap
      ? `\`${h.api}\` is more than one label below \`${h.zone}\`, so the zone's wildcard does **not** cover it.`
      : `\`${h.api}\` is one label below \`${h.zone}\`, so the zone's wildcard covers it.`;
    lines.push(depthNote);
    lines.push("");
  }
  lines.push(
    "This is the constraint that decides where a project's domain can live. When the API host would sit deeper than one label, there are three ways out, cheapest-correct first:",
  );
  lines.push("");
  // Stated even for a project that is fine today: the project about to
  // move its domain under an existing zone is exactly this one.
  const alternatives = layout.wildcardTrap
    ? layout.alternatives
    : wildcardAlternatives(h.api || `api.${h.zone}`, h.zone);
  alternatives.forEach((alt, i) => {
    lines.push(`${i + 1}. **${alt.title}** — ${alt.detail} Cost: ${alt.cost}.`);
  });
  lines.push("");

  lines.push("## Reading a broken deploy");
  lines.push("");
  lines.push("| Symptom | Cause | Where to look |");
  lines.push("| --- | --- | --- |");
  lines.push(
    "| 404 from the API host, while the site works | the matched path prefix was stripped | the application's domain field — make it a bare host with no path |",
  );
  lines.push(
    "| the site's own 404 page from the API host | two applications are claiming the same site | the two applications' domain fields — they must not share a host |",
  );
  lines.push(
    "| a gateway error (502 / 503) from a healthy application | no usable proxy labels were emitted | the service names in the routing entries against the compose file |",
  );
  lines.push(
    "| TLS handshake failure, before any HTTP | the host is more than one label under its zone | the certificate covering that host — a wildcard does not reach it |",
  );
  lines.push("");

  lines.push("## One-time setup on the platform");
  lines.push("");
  if (h.split) {
    lines.push("1. **Two applications**, both from this repository, build pack `dockercompose`:");
    lines.push("");
    for (const app of layout.apps) {
      const file =
        app.role === "server" ? "docker-compose.server.yml" : "docker-compose.client.yml";
      lines.push(
        `   - \`${project.name}-${app.role}\` → compose path \`${file}\`, domain \`https://${app.hosts[0]}\``,
      );
    }
    lines.push("");
    lines.push(
      "   Give each one a bare host and no path (fact 3), and never the same host as the other.",
    );
  } else {
    lines.push(
      `1. **One application** from this repository, build pack \`dockercompose\`, compose path \`docker-compose.yml\`, domain \`https://${h.web || h.api}\`.`,
    );
  }
  lines.push("");
  lines.push(
    `2. **DNS** on the \`${h.zone}\` zone: ${layout.dnsHosts.map((x) => `\`${x}\``).join(" and ")}. Every host an application carries needs a record before its certificate can be issued.`,
  );
  lines.push("");
  lines.push(
    "3. **Environment values on the application that runs the server.** Under a split the API and the site are separate origins, so the cross-origin settings stop being decorative: the server's own public origin, the site's origin, and the trusted-origin list are what make sign-in work at all. Getting them wrong breaks authentication for everyone, not just for one client.",
  );
  lines.push("");
  lines.push(
    "4. **The client's API origin is baked in at image build time.** It is a build argument, not a runtime value: a wrong value builds green and points the shipped bundle at a dead host. Changing it means rebuilding the image.",
  );
  lines.push("");

  lines.push("## Verifying a deploy");
  lines.push("");
  lines.push("```bash");
  if (h.api) lines.push(`curl -sS  ${h.apiOrigin}/api/health   # the server half`);
  if (h.web) lines.push(`curl -sSI ${h.webOrigin}/   # the client half`);
  lines.push("```");
  lines.push("");
  if (h.api) {
    lines.push(
      `The first request covers the whole server chain at once: the certificate on \`${h.api}\`, the route reaching the container with nothing stripped, and the server being up. Read a failure against the table above.`,
    );
    lines.push("");
    lines.push(
      `The API origin is an origin with no path — \`${h.apiOrigin}\` — and the clients append \`/api/...\` themselves. A request therefore reads \`${h.apiOrigin}/api/health\`${h.split ? ", with a doubled-looking `api` segment" : ""}. That is the mount, not a mistake in the value.`,
    );
  } else {
    lines.push("Read a failure against the table above.");
  }
  lines.push("");
  return `${lines.join("\n")}`;
}

// ---------------------------------------------------------------------------
// The CLAUDE.md section
// ---------------------------------------------------------------------------

/** The compact version, in the register of a project's agent-memory
 *  file: dense, reason first, no step-by-step. It is written to be read
 *  by whoever is about to "simplify" the deployment. */
export function renderClaudeMdSection(project: OperationalProject): string {
  const h = hostsOf(project);
  const lines: string[] = [];

  lines.push(CLAUDE_MD_BEGIN);
  lines.push(
    h.split
      ? `### Deployment (two applications, two hosts)`
      : `### Deployment (one application, one host)`,
  );
  lines.push("");
  if (h.split) {
    lines.push(
      `Production is two applications on two hosts of the \`${h.zone}\` zone: the site on \`${h.webOrigin}\` from \`docker-compose.client.yml\`, the API on \`${h.apiOrigin}\` from \`docker-compose.server.yml\`. Two applications rather than one so a site deploy cannot restart the server and drop every connected socket.`,
    );
  } else {
    lines.push(
      `Production is one application on \`${h.webOrigin}\`, from \`docker-compose.yml\`. Both halves restart together, so a site deploy also restarts the server and drops every connection it was holding. Split the deployment before that matters.`,
    );
  }
  lines.push("");
  lines.push(
    `The service name inside each compose file is load-bearing: the platform keys its domain routing by service name, and a key that matches no declared service is accepted with a 200, emits no proxy labels, and serves a gateway error. Success from the API plus a broken site means check the service names first.`,
  );
  lines.push("");
  lines.push(
    "**Never split the halves by path on one host.** The proxy merges same-host site blocks, so one application swallows the other's traffic, and it strips the matched prefix, so the API receives requests one segment short of the mount it serves. Each application gets a host of its own, routed at `/`.",
  );
  lines.push("");
  lines.push(
    `**A wildcard certificate covers one label below its zone.** \`*.${h.zone}\` covers \`${h.api || `api.${h.zone}`}\` only while that host is one label deep; two labels down, TLS fails before any HTTP and nothing downstream is diagnosable. This is what decides where the domain can live — an apex zone of its own is the cheap correct answer.`,
  );
  lines.push("");
  if (h.split) {
    lines.push(
      "Consequence: the API is a separate origin from the site. The cross-origin settings on the server (its own public origin, the site's origin, the trusted-origin list) are load-bearing, not decorative — do not simplify them away. The client's API origin is inlined at image build time, so a wrong value builds green and points at a dead host.",
    );
    lines.push("");
  }
  lines.push(`Full reasoning, symptoms and setup: \`${TOPOLOGY_DOC_REL}\`.`);
  lines.push(CLAUDE_MD_END);
  return lines.join("\n");
}

/** Insert or replace the section in an existing CLAUDE.md.
 *
 *  Three outcomes, and the third is the important one:
 *
 *    · markers present → the text between them is replaced, so running
 *      this twice is the same as running it once.
 *    · no markers, but a deployment-ish heading → the section is
 *      inserted after that section's body, before the next heading at
 *      the same or a higher level.
 *    · neither → the input is returned UNCHANGED. A memory file with no
 *      place for this is a file somebody wrote by hand, and appending
 *      to the end of it is how a generated block ends up stranded in
 *      the middle of unrelated prose. */
export function upsertClaudeMdSection(content: string, section: string): string {
  const begin = content.indexOf(CLAUDE_MD_BEGIN);
  const end = content.indexOf(CLAUDE_MD_END);
  if (begin !== -1 && end !== -1 && end > begin) {
    const head = content.slice(0, begin);
    const tail = content.slice(end + CLAUDE_MD_END.length);
    return `${head}${section}${tail}`;
  }

  const lines = content.split(/\r?\n/);
  const anchor = lines.findIndex((line) => ANCHOR_HEADING.test(line));
  if (anchor === -1) return content;

  const anchorMatch = ANCHOR_HEADING.exec(lines[anchor] ?? "");
  const anchorLevel = anchorMatch?.[1]?.length ?? 2;
  let insertAt = lines.length;
  for (let i = anchor + 1; i < lines.length; i++) {
    const heading = /^(#{1,6})\s/.exec(lines[i] ?? "");
    if (heading && heading[1].length <= anchorLevel) {
      insertAt = i;
      break;
    }
  }

  const before = lines.slice(0, insertAt);
  const after = lines.slice(insertAt);
  while (before.length > 0 && before[before.length - 1]?.trim() === "") before.pop();
  const rebuilt = [...before, "", section, "", ...after];
  return rebuilt.join("\n");
}
