/*
 * Client build-arg wiring — keeps the web client image's NEXT_PUBLIC_*
 * values correct across scaffold / regen-infra / rename-domain.
 *
 * Why this exists: Next.js inlines NEXT_PUBLIC_* env vars into the
 * browser bundle at BUILD time. The deploy pipeline builds the client
 * image once in CI and ships it prebuilt to Coolify, so runtime env on
 * the container can never reach browser code. The only correct channel
 * is Docker build args on the CI image build — and since hatchkit knows
 * the production domain, it writes the URL values straight into the
 * generated workflow as literals.
 *
 * URL shape: single-domain routing (see autoGeneratedDefaults in
 * scaffold/dotenvx.ts) — the bare domain serves the client and the API
 * mounts under /api paths on the same host (Coolify routes
 * https://<domain>/api → server). Same-origin keeps auth cookies and
 * CORS out of the picture entirely.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const CLIENT_WORKFLOW_REL_PATH = ".github/workflows/build-and-deploy.yml";
export const CLIENT_DOCKERFILE_REL_PATH = "packages/client/Dockerfile";

/** Build-time URL values for the client bundle, derived from the
 *  project domain. Bare domain on purpose — see module header. */
export function clientBuildArgUrls(domain: string): { apiUrl: string; wsUrl: string } {
  return { apiUrl: `https://${domain}`, wsUrl: `wss://${domain}` };
}

// ---------------------------------------------------------------------------
// Pure content transforms — unit-testable, used by scaffold (write-through
// wrappers below), regen-infra (diff + write), and rename-domain (FileEdit).
// ---------------------------------------------------------------------------

/** Set the literal NEXT_PUBLIC_API_URL / NEXT_PUBLIC_WS_URL values on an
 *  existing `build-args:` block in build-and-deploy.yml. Anchors on the
 *  `KEY=` line shape that only the build-args block uses (workflow env
 *  blocks use `KEY: value`), so nothing else can match. No-op when the
 *  lines are absent — use upgradeWorkflowClientBuildArgs to insert them. */
export function setWorkflowClientBuildArgUrls(content: string, domain: string): string {
  const { apiUrl, wsUrl } = clientBuildArgUrls(domain);
  return content
    .replace(/^(\s*NEXT_PUBLIC_API_URL=).*$/m, `$1${apiUrl}`)
    .replace(/^(\s*NEXT_PUBLIC_WS_URL=).*$/m, `$1${wsUrl}`);
}

/** Insert the full client `build-args:` block into a build-and-deploy.yml
 *  that predates it, then set the URL values. Anchor: the
 *  `file: packages/client/Dockerfile` + `push: true` pair of the client
 *  image step (the generated workflow's shape is stable). Idempotent —
 *  when a NEXT_PUBLIC_API_URL= line already exists, only the values are
 *  refreshed. Returns the content unchanged when the anchor is missing
 *  (hand-rolled workflow — safer to leave it alone). */
export function upgradeWorkflowClientBuildArgs(content: string, domain: string): string {
  if (/^\s*NEXT_PUBLIC_API_URL=/m.test(content)) {
    return setWorkflowClientBuildArgUrls(content, domain);
  }
  const anchor = /^([ \t]*)file: packages\/client\/Dockerfile\r?\n\1push: true\r?\n/m;
  const m = content.match(anchor);
  if (!m) return content;
  const indent = m[1];
  const block =
    `${indent}# NEXT_PUBLIC_* are inlined into the browser bundle at image\n` +
    `${indent}# BUILD time — setting them as runtime env on the deployed\n` +
    `${indent}# container does nothing. The URL values below are written by\n` +
    `${indent}# hatchkit (kept in sync by \`hatchkit regen-infra\` /\n` +
    `${indent}# \`hatchkit rename-domain\`). The analytics values are optional\n` +
    `${indent}# GitHub Actions repo VARIABLES (not secrets):\n` +
    `${indent}#   gh variable set NEXT_PUBLIC_OPENPANEL_CLIENT_ID ...\n` +
    `${indent}build-args: |\n` +
    `${indent}  NEXT_PUBLIC_API_URL=\n` +
    `${indent}  NEXT_PUBLIC_WS_URL=\n` +
    `${indent}  NEXT_PUBLIC_OPENPANEL_CLIENT_ID=\${{ vars.NEXT_PUBLIC_OPENPANEL_CLIENT_ID }}\n` +
    `${indent}  NEXT_PUBLIC_PLAUSIBLE_DOMAIN=\${{ vars.NEXT_PUBLIC_PLAUSIBLE_DOMAIN }}\n` +
    `${indent}  NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL=\${{ vars.NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL }}\n` +
    `${indent}  NEXT_PUBLIC_SENTRY_DSN=\${{ vars.NEXT_PUBLIC_SENTRY_DSN }}\n`;
  const inserted = content.replace(anchor, `${m[0]}${block}`);
  return setWorkflowClientBuildArgUrls(inserted, domain);
}

/** The ARG/ENV block the client Dockerfile's build stage needs so the
 *  CI build args actually reach `next build`. Mirrors the starter
 *  template — keep the two in sync. */
const DOCKERFILE_BUILD_ARG_BLOCK = `
# Next.js inlines NEXT_PUBLIC_* into the browser bundle at BUILD time —
# runtime env on the deployed container has no effect on browser code.
# CI passes these as --build-arg (see .github/workflows/build-and-deploy.yml).
# HATCHKIT_IMAGE_BUILD makes next.config.ts fail the build loudly when
# NEXT_PUBLIC_API_URL is missing, instead of baking a broken fallback.
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_OPENPANEL_CLIENT_ID
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL
ARG NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \\
    NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL \\
    NEXT_PUBLIC_OPENPANEL_CLIENT_ID=$NEXT_PUBLIC_OPENPANEL_CLIENT_ID \\
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN \\
    NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL=$NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL \\
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \\
    HATCHKIT_IMAGE_BUILD=1

`;

/** Insert the NEXT_PUBLIC_* ARG/ENV block into a client Dockerfile that
 *  predates it. Anchor: the first `RUN pnpm --filter … build` line of
 *  the build stage (workspace scope varies per project, so the filter
 *  target is matched loosely). Idempotent — no-op when the ARG is
 *  already declared or no anchor line exists. */
export function upgradeClientDockerfile(content: string): string {
  if (content.includes("ARG NEXT_PUBLIC_API_URL")) return content;
  const anchor = /^RUN pnpm --filter \S+ run build/m;
  const m = content.match(anchor);
  if (!m || m.index === undefined) return content;
  return (
    content.slice(0, m.index) + DOCKERFILE_BUILD_ARG_BLOCK.trimStart() + content.slice(m.index)
  );
}

/** Remove NEXT_PUBLIC_* entries from docker-compose.yml runtime
 *  `environment:` blocks. They're dead config on a prebuilt image
 *  (Next.js inlined the values when CI built it) and mislead readers
 *  into thinking runtime env reaches the browser bundle. Safe globally:
 *  only the client service ever carried NEXT_PUBLIC_ keys, and any
 *  hand-added ones are equally dead. */
export function stripComposeClientRuntimeNextPublic(content: string): string {
  return content.replace(/^[ \t]*NEXT_PUBLIC_[A-Z0-9_]+:.*\r?\n/gm, "");
}

// ---------------------------------------------------------------------------
// Write-through wrappers
// ---------------------------------------------------------------------------

/** Scaffold-time hook: stamp the project's literal URLs into the
 *  generated workflow's build-args block. No-op when the workflow is
 *  absent (e.g. gh-pages-mode scaffolds). Returns true when written. */
export function applyWorkflowClientBuildArgUrls(outputDir: string, domain: string): boolean {
  const path = join(outputDir, CLIENT_WORKFLOW_REL_PATH);
  if (!existsSync(path)) return false;
  const before = readFileSync(path, "utf-8");
  const after = setWorkflowClientBuildArgUrls(before, domain);
  if (after === before) return false;
  writeFileSync(path, after, "utf-8");
  return true;
}
