/*
 * dotenvx integration for scaffolded projects.
 *
 * Flow at scaffold time:
 *   1. For each key → value mapping the user supplied (prompts OR
 *      presets), call `dotenvx.set(key, value, { encrypt: true, path })`.
 *      On first call, dotenvx generates a fresh ECIES keypair and
 *      writes the public key into `.env.production` + the private
 *      key into `.env.keys`.
 *   2. Read `.env.keys` to pull out DOTENV_PRIVATE_KEY_PRODUCTION and
 *      mirror it into the OS keychain under
 *      `dotenvx:<project-name>:production-private-key`.
 *      The on-disk .env.keys stays (gitignored) for local dev
 *      ergonomics; keychain is the canonical backup + source for
 *      re-deploy.
 *   3. Values the user DIDN'T supply land as plaintext "CHANGE_ME_*"
 *      in .env.production — the user can encrypt them later with
 *      `dotenvx set KEY value -f .env.production`.
 *
 * None of the values (including the generated BETTER_AUTH_SECRET)
 * are ever logged. The private key is printed once via a deferred
 * hint pointing at `hatchkit keys show <project>`.
 */

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { set as dotenvxSet } from "@dotenvx/dotenvx";
import chalk from "chalk";
import ora from "ora";
import type { ProjectConfig } from "../prompts.js";
import { SECRET_KEYS, setSecret } from "../utils/secrets.js";

export interface DotenvxValues {
  /** Values to encrypt into .env.production. User-supplied only —
   *  empty string / undefined = "I'll fill this in later" (then we
   *  write a plaintext CHANGE_ME_<KEY> placeholder instead). */
  [envKey: string]: string | undefined;
}

export interface DotenvxSeedResult {
  /** Full DOTENV_PRIVATE_KEY_PRODUCTION (hex). Stored in keychain. */
  privateKey: string;
  /** Corresponding public key — also embedded at the top of
   *  `.env.production` by dotenvx. Safe to log / commit. */
  publicKey: string;
  /** Keys that ended up as plaintext CHANGE_ME (user didn't supply). */
  placeholderKeys: string[];
  /** Keys that got encrypted. */
  encryptedKeys: string[];
}

/** Set of keys that are always safe to auto-generate if the user
 *  doesn't supply them (cryptographically random, no external
 *  coordination needed). */
function autoGeneratedDefaults(): DotenvxValues {
  return {
    BETTER_AUTH_SECRET: randomBytes(32).toString("hex"),
  };
}

/** Populate the starter's `packages/server/.env.production` with
 *  encrypted values + a plaintext CHANGE_ME_<KEY> for anything the
 *  user didn't supply. Mirrors the generated private key into the
 *  macOS Keychain (or equivalent) and returns it so callers can push
 *  it to Coolify / print a retrieval hint. */
export async function seedDotenvxProduction(
  outputDir: string,
  config: ProjectConfig,
  userValues: DotenvxValues,
): Promise<DotenvxSeedResult> {
  const envPath = join(outputDir, "packages/server/.env.production");
  const envKeysPath = join(outputDir, "packages/server/.env.keys");

  // Determine the full key → value map.
  const defaults = autoGeneratedDefaults();
  const merged: Record<string, string | undefined> = { ...defaults, ...userValues };

  // Every key we want present in .env.production. Includes ones the
  // user didn't supply — those get plaintext CHANGE_ME_<KEY> so
  // misconfigured deploys fail loudly rather than silently running
  // with empty secrets.
  const allKeys = candidateKeys(config);
  const encryptedKeys: string[] = [];
  const placeholderKeys: string[] = [];

  const spinner = ora("Seeding encrypted .env.production").start();
  try {
    for (const key of allKeys) {
      const raw = merged[key];
      const hasValue = raw !== undefined && raw.trim() !== "";
      if (hasValue) {
        dotenvxSet(key, raw, { path: envPath, encrypt: true });
        encryptedKeys.push(key);
      } else {
        // CHANGE_ME_<KEY> is intentionally noisy — anything that tries
        // to use it at runtime will either fail validation (zod /
        // `getRequired`) or point clearly at its own source.
        dotenvxSet(key, `CHANGE_ME_${key}`, { path: envPath, encrypt: false });
        placeholderKeys.push(key);
      }
    }
    spinner.succeed(
      `Seeded .env.production (${encryptedKeys.length} encrypted, ${placeholderKeys.length} placeholders)`,
    );
  } catch (err) {
    spinner.fail("Failed to seed .env.production");
    throw err;
  }

  // Pull the freshly-generated private key out of .env.keys.
  const { privateKey, publicKey } = readKeypair(envKeysPath, envPath);

  // Mirror the private key into the OS keychain. Keep .env.keys on
  // disk too (gitignored) so local `pnpm start` works with no extra
  // steps — the keychain copy is for re-deploy + recovery.
  await setSecret(SECRET_KEYS.dotenvxPrivateKey(config.name), privateKey);

  return { privateKey, publicKey, encryptedKeys, placeholderKeys };
}

/** Keys the scaffolder seeds into .env.production. Extend here when
 *  the starter gains new required env entries. */
function candidateKeys(config: ProjectConfig): string[] {
  const base = ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL", "FRONTEND_URL"];
  // MONGODB_URI is only seeded as a CHANGE_ME placeholder when the
  // user is bringing their own DB — for the Coolify path, hatchkit
  // provisions the container post-deploy and writes the encrypted URL
  // directly, so a CHANGE_ME placeholder would be misleading.
  if (config.mongodbProvider !== "coolify") {
    base.unshift("MONGODB_URI");
  }
  if (config.features.includes("stripe")) {
    base.push("STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET");
  }
  if (config.features.includes("analytics")) {
    base.push("SENTRY_DSN");
  }
  if (config.features.includes("s3")) {
    base.push(
      "S3_ENDPOINT",
      "S3_BUCKET_NAME",
      "S3_PUBLIC_URL",
      "AWS_REGION",
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
    );
  }
  if (config.features.includes("websocket")) {
    base.push("REDIS_URL");
  }
  return base;
}

interface Keypair {
  privateKey: string;
  publicKey: string;
}

/** Parse the generated .env.keys + the header of .env.production to
 *  recover the hex-encoded production keypair. */
function readKeypair(envKeysPath: string, envPath: string): Keypair {
  if (!existsSync(envKeysPath)) {
    throw new Error(
      `dotenvx was expected to create ${envKeysPath}, but it's missing. Nothing was encrypted.`,
    );
  }
  const keysContent = readFileSync(envKeysPath, "utf-8");
  const privateMatch = keysContent.match(/^DOTENV_PRIVATE_KEY_PRODUCTION="?([0-9a-fA-F]+)"?/m);
  if (!privateMatch) {
    throw new Error(`Could not find DOTENV_PRIVATE_KEY_PRODUCTION in ${envKeysPath}.`);
  }

  const envContent = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";
  const publicMatch = envContent.match(/^DOTENV_PUBLIC_KEY_PRODUCTION="?([0-9a-fA-F]+)"?/m);

  return {
    privateKey: privateMatch[1],
    publicKey: publicMatch ? publicMatch[1] : "",
  };
}

/** Prompt the user for the subset of candidate keys that are
 *  sensitive + likely already known at scaffold time. Anything they
 *  leave blank falls through to CHANGE_ME. Skipped entirely in
 *  non-interactive mode — presets should carry the values instead. */
export function printDotenvxSummary(result: DotenvxSeedResult, projectName: string): void {
  if (result.encryptedKeys.length > 0) {
    console.log(
      chalk.green(`  ✓ Encrypted ${result.encryptedKeys.length} values into .env.production`),
    );
  }
  if (result.placeholderKeys.length > 0) {
    console.log(
      chalk.dim(`    Placeholders (edit later with \`dotenvx set KEY value -f .env.production\`):`),
    );
    for (const k of result.placeholderKeys) {
      console.log(chalk.dim(`      ${k}`));
    }
  }
  console.log(
    chalk.yellow(`\n  dotenvx private key stored in macOS Keychain (hatchkit:${projectName}).`),
  );
  console.log(chalk.dim(`  Retrieve anytime:   hatchkit keys show ${projectName}`));
  console.log(chalk.dim(`  Push to Coolify:    hatchkit keys push ${projectName}`));
}
