/*
 * cli/src/scaffold/identifier-agreement.ts — assert that every copy of
 * a project identifier still says the same thing.
 *
 * ============================================================
 * WHY AN ASSERTION AND NOT JUST A TEMPLATE
 * ============================================================
 *
 * A few identifiers have to exist in more than one place, because the
 * platforms that read them do not share a config file:
 *
 *   · the launcher label is in the web app manifest (`short_name`), the
 *     Capacitor config (`appName`), the iOS `Info.plist`
 *     (`CFBundleDisplayName`) and the Android string resources
 *     (`app_name`, `title_activity_main`);
 *   · the bundle id is in the Electron build block (`build.appId`), the
 *     Capacitor config (`appId`), the iOS `Info.plist`
 *     (`CFBundleIdentifier`) and the Android Gradle file
 *     (`applicationId`).
 *
 * Scaffolding writes them all from one source. Nothing keeps them in
 * agreement afterwards: the native trees are generated by `cap add`
 * and then COMMITTED, so they are ordinary files a person edits. A
 * drifted copy does not fail the build — it ships an app whose icon
 * says one thing and whose store listing says another, or, for the
 * bundle id, an upload rejected by the store days later with a message
 * that does not name the file.
 *
 * So the copies are checked, not merely generated. `collectIdentifier
 * Mismatches` reads whichever of these files exist and reports every
 * disagreement with the manifest, naming the file and both values.
 *
 * Reading, not parsing: these files are XML, Gradle DSL, TypeScript and
 * JSON, and pulling in four parsers to read one field each would make a
 * check that runs on every scaffold the slowest thing in it. Each
 * reader below matches the one shape the generator writes and returns
 * `undefined` when it does not find it — an unreadable file produces no
 * finding rather than a false one.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { ProjectIdentifiers } from "./identifiers.js";

export interface IdentifierMismatch {
  /** Project-relative path of the file that disagrees. */
  file: string;
  /** Which identifier disagrees — a `ProjectIdentifiers` key path. */
  field: string;
  /** Where inside the file, e.g. `build.appId` or `<string name="app_name">`. */
  location: string;
  expected: string;
  actual: string;
}

export interface AgreementReport {
  mismatches: IdentifierMismatch[];
  /** Files that were found and successfully read a value from. */
  checked: string[];
  /** Files that exist but whose expected field could not be located.
   *  Reported separately from a mismatch: a hand-restructured file is
   *  a reason to look, not proof of a wrong value. */
  unreadable: string[];
}

interface Probe {
  /** Project-relative file path. */
  file: string;
  /** Pull the concrete values out of the file's text. */
  read: (text: string) => Array<{ field: string; location: string; value: string }>;
  /** Expected value per field. */
  expect: (ids: ProjectIdentifiers) => Record<string, string>;
}

/** First capture group of the first matching pattern, or undefined. */
function firstMatch(text: string, ...patterns: RegExp[]): string | undefined {
  for (const re of patterns) {
    const m = text.match(re);
    if (m?.[1] !== undefined) return m[1];
  }
  return undefined;
}

/** Value of a `<key>NAME</key><string>VALUE</string>` pair in a plist,
 *  tolerating arbitrary whitespace and newlines between the two tags. */
function plistString(text: string, key: string): string | undefined {
  const re = new RegExp(`<key>\\s*${key}\\s*</key>\\s*<string>([^<]*)</string>`);
  return text.match(re)?.[1];
}

/** Value of `<string name="NAME">VALUE</string>` in an Android string
 *  resource file. */
function androidString(text: string, name: string): string | undefined {
  const re = new RegExp(`<string\\s+name="${name}"[^>]*>([^<]*)</string>`);
  return text.match(re)?.[1];
}

const PROBES: Probe[] = [
  {
    file: "package.json",
    read: (text) => {
      const out: Array<{ field: string; location: string; value: string }> = [];
      let pkg: Record<string, unknown>;
      try {
        pkg = JSON.parse(text) as Record<string, unknown>;
      } catch {
        return out;
      }
      const build = pkg.build as Record<string, unknown> | undefined;
      if (typeof build?.appId === "string") {
        out.push({ field: "bundleId", location: "build.appId", value: build.appId });
      }
      if (typeof build?.productName === "string") {
        out.push({ field: "productName", location: "build.productName", value: build.productName });
      }
      return out;
    },
    expect: (ids) => ({ bundleId: ids.bundleId, productName: ids.productName }),
  },
  {
    file: "capacitor.config.ts",
    read: (text) => {
      const out: Array<{ field: string; location: string; value: string }> = [];
      const appId = firstMatch(text, /appId:\s*["'`]([^"'`]+)["'`]/);
      if (appId) out.push({ field: "bundleId", location: "appId", value: appId });
      // Capacitor's `appName` is what the launcher shows, so it is the
      // SHORT name, not the product name. `cap add` copies it straight
      // into CFBundleDisplayName and the Android app_name.
      const appName = firstMatch(text, /appName:\s*["'`]([^"'`]+)["'`]/);
      if (appName) out.push({ field: "shortName", location: "appName", value: appName });
      return out;
    },
    expect: (ids) => ({ bundleId: ids.bundleId, shortName: ids.shortName }),
  },
  {
    file: "packages/client/public/manifest.json",
    read: (text) => {
      const out: Array<{ field: string; location: string; value: string }> = [];
      let m: Record<string, unknown>;
      try {
        m = JSON.parse(text) as Record<string, unknown>;
      } catch {
        return out;
      }
      if (typeof m.name === "string")
        out.push({ field: "productName", location: "name", value: m.name });
      if (typeof m.short_name === "string") {
        out.push({ field: "shortName", location: "short_name", value: m.short_name });
      }
      return out;
    },
    expect: (ids) => ({ productName: ids.productName, shortName: ids.shortName }),
  },
  {
    file: "ios/App/App/Info.plist",
    read: (text) => {
      const out: Array<{ field: string; location: string; value: string }> = [];
      const display = plistString(text, "CFBundleDisplayName");
      if (display)
        out.push({ field: "shortName", location: "CFBundleDisplayName", value: display });
      const id = plistString(text, "CFBundleIdentifier");
      // Xcode's default is the build-setting reference rather than a
      // literal; that is not drift, it resolves to the project's
      // PRODUCT_BUNDLE_IDENTIFIER, which the Gradle/pbxproj probe below
      // does not cover. Skip rather than report a false mismatch.
      if (id && !id.includes("$(")) {
        out.push({ field: "bundleId", location: "CFBundleIdentifier", value: id });
      }
      return out;
    },
    expect: (ids) => ({ shortName: ids.shortName, bundleId: ids.bundleId }),
  },
  {
    file: "ios/App/App.xcodeproj/project.pbxproj",
    read: (text) => {
      const id = firstMatch(text, /PRODUCT_BUNDLE_IDENTIFIER\s*=\s*"?([A-Za-z0-9.\-_]+)"?\s*;/);
      return id ? [{ field: "bundleId", location: "PRODUCT_BUNDLE_IDENTIFIER", value: id }] : [];
    },
    expect: (ids) => ({ bundleId: ids.bundleId }),
  },
  {
    file: "android/app/build.gradle",
    read: (text) => {
      const id = firstMatch(
        text,
        /applicationId\s+["']([^"']+)["']/,
        /applicationId\s*=\s*["']([^"']+)["']/,
      );
      return id ? [{ field: "bundleId", location: "applicationId", value: id }] : [];
    },
    expect: (ids) => ({ bundleId: ids.bundleId }),
  },
  {
    file: "android/app/src/main/res/values/strings.xml",
    read: (text) => {
      const out: Array<{ field: string; location: string; value: string }> = [];
      const appName = androidString(text, "app_name");
      if (appName)
        out.push({ field: "shortName", location: '<string name="app_name">', value: appName });
      // Capacitor's generated Android project shows `title_activity_main`
      // in the recents switcher. It is generated equal to app_name and
      // silently diverges when only one is edited.
      const title = androidString(text, "title_activity_main");
      if (title) {
        out.push({
          field: "shortName",
          location: '<string name="title_activity_main">',
          value: title,
        });
      }
      const pkg = androidString(text, "package_name");
      if (pkg)
        out.push({ field: "bundleId", location: '<string name="package_name">', value: pkg });
      const customUrl = androidString(text, "custom_url_scheme");
      if (customUrl) {
        out.push({
          field: "bundleId",
          location: '<string name="custom_url_scheme">',
          value: customUrl,
        });
      }
      return out;
    },
    expect: (ids) => ({ shortName: ids.shortName, bundleId: ids.bundleId }),
  },
];

/**
 * Compare every identifier copy present in `projectDir` against `ids`.
 *
 * Absent files are skipped silently — a web-only project has no
 * `ios/` tree, and that is not a finding.
 */
export function collectIdentifierMismatches(
  projectDir: string,
  ids: ProjectIdentifiers,
): AgreementReport {
  const mismatches: IdentifierMismatch[] = [];
  const checked: string[] = [];
  const unreadable: string[] = [];

  for (const probe of PROBES) {
    const abs = join(projectDir, probe.file);
    if (!existsSync(abs)) continue;
    let text: string;
    try {
      text = readFileSync(abs, "utf-8");
    } catch {
      unreadable.push(probe.file);
      continue;
    }
    const found = probe.read(text);
    if (found.length === 0) {
      unreadable.push(probe.file);
      continue;
    }
    checked.push(probe.file);
    const expectations = probe.expect(ids);
    for (const { field, location, value } of found) {
      const expected = expectations[field];
      if (expected === undefined) continue;
      if (value !== expected) {
        mismatches.push({ file: probe.file, field, location, expected, actual: value });
      }
    }
  }

  return { mismatches, checked, unreadable };
}

/** Throw when any copy disagrees. Used by the scaffold's own
 *  post-write check and by the test suite; `hatchkit doctor` calls
 *  {@link collectIdentifierMismatches} directly so it can report every
 *  mismatch at once rather than stopping at the first. */
export function assertIdentifierAgreement(projectDir: string, ids: ProjectIdentifiers): void {
  const { mismatches } = collectIdentifierMismatches(projectDir, ids);
  if (mismatches.length === 0) return;
  const lines = mismatches.map(
    (m) =>
      `  · ${m.file} (${m.location}): expected ${JSON.stringify(m.expected)}, found ${JSON.stringify(m.actual)}`,
  );
  throw new Error(
    `Project identifiers disagree across files. The manifest is the source of truth:\n${lines.join("\n")}`,
  );
}

/** One-line-per-mismatch rendering for CLI output. */
export function formatIdentifierMismatches(mismatches: IdentifierMismatch[]): string[] {
  return mismatches.map(
    (m) => `${m.file} → ${m.location}: expected "${m.expected}", found "${m.actual}" (${m.field})`,
  );
}
