/*
 * The mobile (Capacitor) feature's file, script and dependency manifest —
 * the ONE place that knows what the feature consists of.
 *
 * Three call sites consume it and must never disagree:
 *
 *   · scaffold/app.ts     strips every entry when `mobile` is not selected
 *   · scaffold/update.ts  copies every entry when `mobile` is added later
 *   · scaffold/surfaces.ts drops the scripts for a backend-only surface
 *
 * The failure mode a shared list prevents is asymmetry. A file added to
 * the starter and listed only in the strip is silently absent from every
 * `hatchkit update`; listed only in the add, it is left behind in every
 * scaffold that declined the feature, where it references modules and
 * packages that were removed — and the project fails its first build.
 *
 * Pure: no I/O, no chalk, no network — safe to import from anywhere.
 */

/** Paths (relative to the project root) that exist only because the
 *  mobile feature is on. Directories and files both; removal is
 *  recursive. Ordered roughly outside-in so a read of this list reads
 *  like a description of the feature. */
export const MOBILE_PATHS: readonly string[] = [
  // The committed native projects. Generated by `pnpm cap:add:*`, then
  // hand-edited (ATS exception, orientations, debug cleartext config,
  // version wiring, signing config) and committed — see starter/.gitignore.
  "ios",
  "android",
  "capacitor.config.ts",

  // Build + release tooling. scripts/build-mobile.mjs is the only
  // supported entry point for a mobile build.
  "scripts/build-mobile.mjs",
  "scripts/cap-add.mjs",
  "scripts/mobile-headless.sh",
  "scripts/lib/mobile-build.mjs",
  "scripts/lib/mobile-release.mjs",
  "scripts/lib/native-overlay.mjs",
  "scripts/android-dev.sh",
  "scripts/android-env.sh",
  "scripts/ios-dev.sh",
  ".github/workflows/mobile-release.yml",
  "resources",

  // Client runtime. The whole `src/mobile` tree, plus the two files that
  // live outside it because of what they are rather than where they run.
  "packages/client/src/mobile",
  // The session token belongs in the platform keychain, not the
  // preference store and not web storage — it is a credential.
  "packages/client/src/lib/native-session.ts",
  "packages/client/src/lib/native-session.test.ts",
  // The dialog primitive is where the overlay stack is registered, once,
  // rather than at every call site. It arrives with the feature and goes
  // with it: without mobile/overlay-stack.ts it would not compile, and a
  // scaffold that declined mobile is back exactly where it started.
  "packages/client/src/components/ui/dialog.tsx",

  // Native chrome. Inert on web by construction (`html.cap`), but only
  // because the marker exists — which it does not without the feature.
  "packages/client/src/styles/native.css",
  // Not inert by construction: an installed web app gets real insets from
  // the shared `viewport-fit=cover`, and this is what handles them.
  "packages/client/src/styles/standalone.css",
];

/** Root package.json scripts the feature owns. */
export const MOBILE_SCRIPTS: readonly string[] = [
  "dev:android",
  "dev:ios",
  "build:mobile",
  "cap:add:ios",
  "cap:add:android",
  "cap:overlay",
  "cap:run:ios",
  "cap:run:android",
  "mobile:headless:ios",
  "mobile:headless:android",
  "build:ios:release",
  "build:android:release",
  "build:android:apk",
  "mobile:assets",
  // Retired: a bare `cap sync` skips every check scripts/build-mobile.mjs
  // performs. Kept in the strip list so projects scaffolded before that
  // change lose the script when they are updated.
  "cap:sync",
];

/** Dependencies the feature owns, across `dependencies` and
 *  `devDependencies` (the strip and the merge both search both). */
export const MOBILE_DEPS: readonly string[] = [
  "@capacitor/core",
  "@capacitor/cli",
  "@capacitor/ios",
  "@capacitor/android",
  "@capacitor/splash-screen",
  "@capacitor/status-bar",
  "@capacitor/screen-orientation",
  "@capacitor/preferences",
  "@capacitor/app",
  "@capacitor/assets",
  // The radio, not the browser flag. `navigator.onLine` reports true on a
  // dead radio in WKWebView and never fires for airplane mode.
  "@capacitor/network",
  // The platform keychain. The preference store is plain UserDefaults and
  // readable from an unencrypted backup, so a credential cannot live there.
  "@aparajita/capacitor-secure-storage",
];

/** Files inside the committed native trees that a `cap sync` (i.e. every
 *  `pnpm build:mobile`) rewrites. A diff here after a build is normal —
 *  commit it when the plugin set changed. Documentation, surfaced by
 *  `hatchkit explain` and the generated CLAUDE.md, so the two can never
 *  drift from each other. */
export const NATIVE_GENERATED_TRACKED: readonly string[] = [
  "ios/App/CapApp-SPM/Package.swift",
  "ios/App/App/Assets.xcassets/",
  "android/capacitor.settings.gradle",
  "android/app/capacitor.build.gradle",
  "android/app/src/main/res/",
];

/** Generated and NOT tracked. A checkout that has never run
 *  `pnpm build:mobile` has none of these, and therefore cannot be opened
 *  in Xcode or Gradle at all — build first. */
export const NATIVE_GENERATED_UNTRACKED: readonly string[] = [
  "ios/App/App/public/",
  "android/app/src/main/assets/public/",
  "android/capacitor-cordova-android-plugins/",
];
