/*
 * Per-half compose files for the `split` deployment topology.
 *
 * Why these exist: a `split` project has TWO Coolify applications, and
 * Coolify builds each one from the `docker_compose_location` on that
 * app. Pointing both at the root `docker-compose.yml` would run the
 * whole four-service stack twice — two clients, two servers, and two
 * mongos racing for the same volume. So each half gets a compose file
 * declaring exactly one service.
 *
 * The service names stay `client` and `server`, matching what
 * deploy/routing.ts puts in `docker_compose_domains` and what
 * `hatchkit sync` validates against. Renaming them here would
 * reintroduce the phantom-service failure mode: Coolify accepts a
 * routing entry naming a service the compose doesn't declare with a
 * 200 OK and then emits no Traefik labels at all.
 *
 * Datastores: `split` does NOT put mongo/redis in either compose file.
 * They'd have to live in one half's stack and be unreachable from the
 * other — the two apps get separate Docker networks. They're
 * provisioned as Coolify-managed databases instead, and their URLs
 * arrive through the encrypted `.env.production` (MONGODB_URI /
 * REDIS_URL), which is why the server compose reads them from env with
 * no fallback rather than hardcoding `mongodb://mongo:27017` the way
 * the single-origin compose can.
 *
 * The root `docker-compose.yml` is left in place either way: it's what
 * `docker compose up` gives a developer locally, and what a project
 * switching back to `single-origin` needs.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { listComposeServices } from "../utils/compose.js";

export const SPLIT_CLIENT_COMPOSE_REL = "docker-compose.client.yml";
export const SPLIT_SERVER_COMPOSE_REL = "docker-compose.server.yml";

export interface SplitComposeResult {
  /** Relative paths actually written. Empty when both already existed. */
  written: string[];
  /** Relative paths left alone because a file was already there — we
   *  never overwrite one the user may have edited. */
  kept: string[];
}

/** Extract one service's block out of a compose file, verbatim.
 *
 * Verbatim on purpose: the block carries the project's real image ref,
 * port pin and full environment list, all of which scaffold/adopt have
 * already substituted. Re-deriving them here would be a second source
 * of truth that drifts the first time either changes.
 *
 * Returns null when the service isn't declared, so the caller can fall
 * back to a minimal stub rather than writing an empty compose. */
export function extractComposeService(content: string, service: string): string | null {
  const lines = content.split(/\r?\n/);
  let servicesIndent = -1;
  let inServices = false;
  let serviceIndent = -1;
  const out: string[] = [];
  let capturing = false;

  for (const raw of lines) {
    const stripped = raw.replace(/#.*$/, "").trimEnd();
    if (!stripped.trim()) {
      if (capturing) out.push(raw);
      continue;
    }
    const indent = stripped.length - stripped.trimStart().length;

    if (!inServices) {
      if (/^services\s*:/.test(stripped)) {
        inServices = true;
        servicesIndent = indent;
      }
      continue;
    }
    if (indent <= servicesIndent) break;

    const key = stripped.match(/^\s*([A-Za-z0-9_.-]+)\s*:\s*$/);
    if (capturing) {
      // A sibling key at the same indent ends this service's block.
      if (key && indent === serviceIndent) break;
      if (indent <= serviceIndent && key) break;
      out.push(raw);
      continue;
    }
    if (key && key[1] === service) {
      capturing = true;
      serviceIndent = indent;
      out.push(raw);
    }
  }

  if (!capturing) return null;
  // Trim trailing blank lines picked up before the next top-level key.
  while (out.length > 0 && !out[out.length - 1].trim()) out.pop();
  return out.join("\n");
}

const HEADER = `# Generated by hatchkit for the \`split\` deployment topology.
#
# This half runs as its own Coolify application, so it declares ONE
# service. The root docker-compose.yml still describes the full local
# stack — this file exists because Coolify builds each application from
# its own docker_compose_location, and pointing both halves at the root
# file would run the whole stack twice.
#
# Do NOT rename the service: hatchkit routes \`docker_compose_domains\`
# by service name, and Coolify accepts a name that isn't in the compose
# with a 200 OK and then emits no Traefik labels at all.
`;

/** Minimal stub used when the root compose has no such service (a
 *  surface-pruned project, or a hand-authored compose we couldn't
 *  match). Keeps the deploy shape valid; the user fills in the image. */
function stubService(service: "client" | "server", imageRef: string, port: number): string {
  return `  ${service}:\n    image: \${${service.toUpperCase()}_IMAGE:-${imageRef}}\n    environment:\n      PORT: "${port}"\n    restart: unless-stopped`;
}

/** Write `docker-compose.client.yml` and `docker-compose.server.yml`
 *  from the project's root compose. Idempotent and non-destructive: an
 *  existing file is never overwritten, because the user may have
 *  tuned it. */
export function writeSplitComposeFiles(args: {
  projectDir: string;
  /** GHCR image stem, e.g. `ghcr.io/owner/project`. Only used for the
   *  stub path when the root compose has no matching service. */
  imageStem: string;
  ports: { server: number; client: number };
  /** Which halves this project actually has. */
  surfaces?: "fullstack" | "split" | "backend" | "static";
}): SplitComposeResult {
  const { projectDir, imageStem, ports } = args;
  const root = ["docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"]
    .map((n) => join(projectDir, n))
    .find((p) => existsSync(p));
  const rootContent = root ? readFileSync(root, "utf-8") : "";
  const declared = rootContent ? listComposeServices(rootContent) : [];

  const halves: Array<{ service: "client" | "server"; rel: string; port: number }> = [];
  if (args.surfaces !== "backend") {
    halves.push({ service: "client", rel: SPLIT_CLIENT_COMPOSE_REL, port: ports.client });
  }
  if (args.surfaces !== "static") {
    halves.push({ service: "server", rel: SPLIT_SERVER_COMPOSE_REL, port: ports.server });
  }

  const written: string[] = [];
  const kept: string[] = [];
  for (const half of halves) {
    const path = join(projectDir, half.rel);
    if (existsSync(path)) {
      kept.push(half.rel);
      continue;
    }
    const block =
      (declared.includes(half.service) ? extractComposeService(rootContent, half.service) : null) ??
      stubService(half.service, `${imageStem}-${half.service}:main`, half.port);
    // The server half loses its compose-network datastores — under
    // `split` those are Coolify-managed databases reachable only via
    // the URLs in the encrypted .env.production.
    const body = half.service === "server" ? rewriteDatastoreEnvForSplit(block) : block;
    writeFileSync(path, `${HEADER}\nservices:\n${body}\n`, "utf-8");
    written.push(half.rel);
  }
  return { written, kept };
}

/** Point MONGODB_URI / REDIS_URL at env instead of the compose-network
 *  hostnames, and drop the `depends_on` that referenced the services
 *  this file no longer declares (compose refuses to start otherwise).
 *
 *  No `:-default` fallback on purpose: under `split` there is no
 *  in-stack mongo to fall back TO, so a missing value should fail the
 *  container loudly rather than have it retry forever against a host
 *  that doesn't exist. */
export function rewriteDatastoreEnvForSplit(block: string): string {
  return block
    .replace(/^(\s*MONGODB_URI:).*$/m, "$1 ${MONGODB_URI}")
    .replace(/^(\s*REDIS_URL:).*$/m, "$1 ${REDIS_URL}")
    .replace(/^(\s*POSTGRES_URL:).*$/m, "$1 ${POSTGRES_URL}")
    .replace(/^[ \t]*depends_on:[ \t]*\r?\n(?:[ \t]*-[ \t]*\S+[ \t]*\r?\n)*/m, "");
}
