/*
 * Per-file customization helpers for scaffoldApp.
 *
 * These edits run after the starter has been copied into the output
 * directory. Each helper is a pure function over one file (or a small
 * group of files), so they're easy to unit-test in isolation.
 */

import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ProjectConfig } from "../prompts.js";
import type { ProjectPorts } from "../utils/ports.js";
import { nativeClientOrigins } from "./native-origins.js";
import { readPackageName, readWorkspacePackageNames, setPackageJsonScript } from "./pkg-json.js";

/** Literal string replacement across a file. Safe for any content —
 *  `replaceAll` is literal (no regex interpretation). */
export function replaceInFile(filePath: string, search: string, replace: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, "utf-8");
  writeFileSync(filePath, content.replaceAll(search, replace), "utf-8");
}

/** Rewrite a file via a pure transform. No-op if the file is missing. */
export function rewriteFile(path: string, fn: (content: string) => string): void {
  if (!existsSync(path)) return;
  const content = readFileSync(path, "utf-8");
  writeFileSync(path, fn(content), "utf-8");
}

export function removeIfExists(path: string): void {
  if (existsSync(path)) {
    rmSync(path, { recursive: true, force: true });
  }
}

/** Rewrite a server or client .env.example to use production URLs for
 *  the project's domain. Swaps in TRUSTED_ORIGINS for native clients
 *  when desktop or mobile is selected. Idempotent on repeat runs. */
export function updateEnvExample(outputDir: string, relPath: string, config: ProjectConfig): void {
  const path = join(outputDir, relPath);
  if (!existsSync(path)) return;

  const { domain } = config;
  // Single-domain routing (matches autoGeneratedDefaults in dotenvx.ts):
  // the bare domain serves the client and the API mounts under /api on
  // the same host — Coolify routes https://<domain>/api → server. Keeping
  // every URL on one origin avoids cross-subdomain cookie/CORS handling.
  const appUrl = `https://${domain}`;
  const apiUrl = `https://${domain}`;
  const wsUrl = `wss://${domain}`;

  let content = readFileSync(path, "utf-8");

  // Targeted line-level rewrites. Each regex anchors on `KEY=` so stray
  // "localhost" mentions inside comments / other keys aren't affected.
  const rewrites: Array<[RegExp, string]> = [
    [/^FRONTEND_URL=.*$/m, `FRONTEND_URL=${appUrl}`],
    [/^BETTER_AUTH_URL=.*$/m, `BETTER_AUTH_URL=${apiUrl}`],
    [/^NEXT_PUBLIC_API_URL=.*$/m, `NEXT_PUBLIC_API_URL=${apiUrl}`],
    [/^NEXT_PUBLIC_WS_URL=.*$/m, `NEXT_PUBLIC_WS_URL=${wsUrl}`],
  ];
  for (const [re, replacement] of rewrites) {
    content = content.replace(re, replacement);
  }

  // Pre-populate TRUSTED_ORIGINS for native clients so the commented
  // guidance in the starter's .env.example is replaced with a working
  // default. The list comes from `nativeClientOrigins`, the same function
  // deploy/trusted-origins.ts merges onto the server's Coolify app — this
  // file is documentation for local setups, Coolify is what production
  // reads, and the two must not drift.
  const origins = nativeClientOrigins(config.features);
  if (origins.length > 0 && /^#\s*TRUSTED_ORIGINS=/m.test(content)) {
    content = content.replace(/^#\s*TRUSTED_ORIGINS=.*$/m, `TRUSTED_ORIGINS=${origins.join(",")}`);
  }

  writeFileSync(path, content, "utf-8");
}

/** Strip the MobileBridgeLoader import + mount from the client layout
 *  when mobile isn't selected. Leaves the rest of the layout alone. */
export function stripMobileBridgeFromLayout(outputDir: string): void {
  const path = join(outputDir, "packages/client/src/app/layout.tsx");
  if (!existsSync(path)) return;
  let content = readFileSync(path, "utf-8");
  content = content.replace(
    /import\s*\{\s*MobileBridgeLoader\s*\}\s*from\s*["']@\/mobile\/MobileBridgeLoader["'];\n/,
    "",
  );
  content = content.replace(/\s*<MobileBridgeLoader\s*\/>\n/, "\n");
  writeFileSync(path, content, "utf-8");
}

/** Overwrite `packages/client/next.config.ts` with a known-good
 *  static-export config. `transpilePackages` is populated from the
 *  actual workspace package names so a starter rename doesn't break
 *  the exported client build.
 *
 *  The generated config keeps the starter's NEXT_PUBLIC_API_URL guard
 *  (see starter/packages/client/next.config.ts). It has to: this file
 *  REPLACES the starter's, and a static export has no runtime env and no
 *  usable same-origin fallback (the desktop shell serves the export from
 *  `file://`, whose origin is opaque). Without the guard `pnpm
 *  build:desktop` succeeds with no API URL and ships a binary that fails
 *  on its first request — a build-time error turned into a runtime one.
 *  The guard is skipped under `next dev`, where the dev server proxies
 *  `/api` and the export path is never taken. */
export function flipNextConfigToStaticExport(outputDir: string): void {
  const path = join(outputDir, "packages/client/next.config.ts");
  if (!existsSync(path)) return;
  const clientName = readPackageName(join(outputDir, "packages/client"));
  const transpile = readWorkspacePackageNames(outputDir).filter((n) => n !== clientName);
  const transpileList = transpile.map((n) => `"${n}"`).join(", ");
  const staticExportConfig = `import type { NextConfig } from "next";

const isDev = process.env.NODE_ENV === "development";

// This client always builds as a static export: the bundle ships inside the
// desktop/mobile shell and the Express server is always remote. Next.js
// inlines NEXT_PUBLIC_* at BUILD time, and a shell loading the export from
// file:// has an opaque origin — there is no same-origin fallback and no
// container env to repair the value later. A build without NEXT_PUBLIC_API_URL
// therefore produces a binary that installs fine and fails on every request,
// so fail loudly here instead. Set it as env on the build step in
// .github/workflows/desktop-release.yml / tauri-release.yml /
// mobile-release.yml (and on any local \`pnpm build:desktop\`).
// \`next dev\` is exempt: it proxies /api to the dev server.
if (!isDev && !process.env.NEXT_PUBLIC_API_URL) {
  throw new Error(
    "NEXT_PUBLIC_API_URL is not set. This is a static-export build whose " +
      "output ships to users, and Next.js bakes NEXT_PUBLIC_* values in at " +
      "build time. Pass it as env on the build step (desktop/mobile release " +
      "workflows in .github/workflows/). Runtime env cannot fix this.",
  );
}

const nextConfig: NextConfig = {
  output: "export",
  assetPrefix: "./",
  trailingSlash: true,
  images: { unoptimized: true },
  transpilePackages: [${transpileList}],
};

export default nextConfig;
`;
  writeFileSync(path, staticExportConfig, "utf-8");
}

/** The exact FRONTEND_URL that the starter template ships in
 *  `packages/server/.env.development`. Doubles as a "this line is still
 *  pristine" sentinel: `applyPorts` retargets FRONTEND_URL only when it
 *  still holds this value, which is true on a first scaffold (the file was
 *  just copied out of `starter/`) and false for any project whose owner has
 *  touched it. Keep in sync with starter/packages/server/.env.development. */
const STARTER_DEFAULT_FRONTEND_URL = "http://localhost:3000";

/** Rewrite every file in the starter that hard-codes the old default
 *  ports (3000/5000) so each scaffolded project has its own coherent
 *  port set. Targets covered:
 *    • packages/server/.env.development       (PORT + BETTER_AUTH_URL → server;
 *                                               FRONTEND_URL → client, but only
 *                                               while it still holds the starter
 *                                               default — see below)
 *    • packages/server/.env.example           (PORT line added)
 *    • packages/client/.env.development       (PORT + API + WS URLs)
 *    • packages/client/.env.example           (PORT line added)
 *    • packages/server/Dockerfile             (ENV PORT, EXPOSE)
 *    • packages/client/Dockerfile             (ENV PORT, EXPOSE)
 *    • docker-compose.yml                      (server PORT env)
 *    • scripts/dev.mjs                         (fixed-mode defaults)
 *    • electron/main.ts                        (DEV_URL fallback)
 *    • src-tauri/tauri.conf.json              (build.devUrl + beforeDevCommand PORT)
 *    • scripts/android-dev.sh + ios-dev.sh    (NEXT_PORT default)
 *    • package.json dev:desktop script        (Next port + wait-on)
 */
export function applyPorts(
  outputDir: string,
  ports: ProjectPorts,
  opts: { wantsDesktop: boolean; wantsTauri?: boolean; wantsMobile: boolean },
): void {
  const { server, client, nativeHmr } = ports;

  // .env.development (server) — set PORT + update URLs pointing at localhost:5000
  rewriteFile(join(outputDir, "packages/server/.env.development"), (c) => {
    let out = c;
    if (/^PORT=/m.test(out)) {
      out = out.replace(/^PORT=.*$/m, `PORT=${server}`);
    } else {
      out = `PORT=${server}\n${out}`;
    }
    out = out.replace(/localhost:5000/g, `localhost:${server}`);
    // FRONTEND_URL is the *client* origin, so the localhost:5000 sweep above
    // never touches it, and left at the starter's 3000 it names a port no
    // scaffolded project runs Next on.
    //
    // Where it actually matters: only when the server is started on its own
    // (`pnpm --filter @starter/server dev`, or any `tsx src/index.ts`).
    // `scripts/dev.mjs` already passes FRONTEND_URL=http://127.0.0.1:<client>
    // in the child's env, and dotenvx does not overload keys already present
    // in process.env — so under `pnpm dev` the value in this file is never
    // consulted. Standalone, getTrustedOrigins()
    // (packages/server/src/config/env.ts) feeds it straight to better-auth and
    // CORS, and a stale 3000 rejects the real dev client as an untrusted
    // origin.
    //
    // Host is `localhost`, deliberately not the `127.0.0.1` dev.mjs uses:
    // browsers treat the two as distinct origins, and `localhost:<port>` is
    // what `next dev` prints and what a developer actually opens. (The two
    // therefore stay divergent between the two dev modes; dev.mjs supplies its
    // own value in the mode it owns.)
    //
    // Rewrite ONLY when the line still holds the untouched starter default.
    // applyPorts also runs from `hatchkit server add` and `hatchkit update`,
    // against repos that already exist and may have been hand-edited (or may
    // not be Hatchkit-shaped at all). Any other value is a user decision and
    // is left alone; when the key is absent nothing is injected, for the same
    // reason. On a first scaffold the file was just copied out of `starter/`,
    // so the sentinel always matches and the allocated client port lands.
    const frontendUrl = /^FRONTEND_URL=(.*)$/m.exec(out);
    if (frontendUrl?.[1].trim() === STARTER_DEFAULT_FRONTEND_URL) {
      out = out.replace(/^FRONTEND_URL=.*$/m, `FRONTEND_URL=http://localhost:${client}`);
    }
    return out;
  });

  // .env.development (client) — set PORT + API/WS URLs
  rewriteFile(join(outputDir, "packages/client/.env.development"), (c) => {
    let out = c;
    if (/^PORT=/m.test(out)) {
      out = out.replace(/^PORT=.*$/m, `PORT=${client}`);
    } else {
      out = `PORT=${client}\n${out}`;
    }
    out = out.replace(
      /^NEXT_PUBLIC_API_URL=.*$/m,
      `NEXT_PUBLIC_API_URL=http://localhost:${server}`,
    );
    out = out.replace(/^NEXT_PUBLIC_WS_URL=.*$/m, `NEXT_PUBLIC_WS_URL=ws://localhost:${server}`);
    return out;
  });

  // .env.example files: add PORT line if missing, else overwrite.
  for (const [rel, port] of [
    ["packages/server/.env.example", server] as const,
    ["packages/client/.env.example", client] as const,
  ]) {
    rewriteFile(join(outputDir, rel), (c) => {
      if (/^PORT=/m.test(c)) return c.replace(/^PORT=.*$/m, `PORT=${port}`);
      return `PORT=${port}\n${c}`;
    });
  }

  // Server + client Dockerfiles: port-bearing lines.
  rewriteFile(join(outputDir, "packages/server/Dockerfile"), (c) =>
    c
      .replace(/ENV PORT=\d+/g, `ENV PORT=${server}`)
      .replace(/EXPOSE \d+/g, `EXPOSE ${server}`)
      .replace(/\|\|'\d+'\)/g, `||'${server}')`),
  );
  rewriteFile(join(outputDir, "packages/client/Dockerfile"), (c) =>
    c
      .replace(/ENV PORT=\d+/g, `ENV PORT=${client}`)
      .replace(/EXPOSE \d+/g, `EXPOSE ${client}`)
      .replace(/\|\|'\d+'\)/g, `||'${client}')`),
  );

  // docker-compose.yml: server PORT first (appears first in file),
  // then the client PORT if present.
  rewriteFile(join(outputDir, "docker-compose.yml"), (c) => {
    let out = c.replace(/PORT:\s*"3000"/, `PORT: "${server}"`);
    out = out.replace(/PORT:\s*"3000"/, `PORT: "${client}"`);
    return out;
  });

  // scripts/dev.mjs: bump fixed-mode defaults + the comment header
  // that documents the default ports.
  rewriteFile(join(outputDir, "scripts/dev.mjs"), (c) =>
    c
      .replace(/clientPort = 3000/g, `clientPort = ${client}`)
      .replace(/apiPort = 5000/g, `apiPort = ${server}`)
      .replace(
        /client 3000, docs 4000, server 5000/g,
        `client ${client}, docs 4000, server ${server}`,
      ),
  );

  // Native HMR port — only wired when desktop or mobile is selected.
  if (nativeHmr === undefined) return;

  rewriteFile(join(outputDir, "electron/main.ts"), (c) =>
    c.replace(
      /const DEV_URL = process\.env\.ELECTRON_DEV_URL \|\| "http:\/\/localhost:\d+"/,
      `const DEV_URL = process.env.ELECTRON_DEV_URL || "http://localhost:${nativeHmr}"`,
    ),
  );

  // Tauri: the dev URL + the PORT the beforeDevCommand starts the Next
  // dev server on both live in tauri.conf.json. Same nativeHmr port as
  // the electron DEV_URL rewrite above.
  rewriteFile(join(outputDir, "src-tauri/tauri.conf.json"), (c) =>
    c
      .replace(/"devUrl":\s*"http:\/\/localhost:\d+"/, `"devUrl": "http://localhost:${nativeHmr}"`)
      .replace(/"beforeDevCommand":\s*"PORT=\d+ /, `"beforeDevCommand": "PORT=${nativeHmr} `),
  );

  for (const script of ["scripts/android-dev.sh", "scripts/ios-dev.sh"]) {
    rewriteFile(join(outputDir, script), (c) =>
      c.replace(/NEXT_PORT="\$\{NEXT_PORT:-\d+\}"/, `NEXT_PORT="\${NEXT_PORT:-${nativeHmr}}"`),
    );
  }

  // Root package.json: dev:desktop needs PORT + wait-on retargeted at
  // nativeHmr so web-dev and desktop-dev don't stomp each other.
  if (opts.wantsDesktop) {
    const clientPkgName = readPackageName(join(outputDir, "packages/client")) ?? "@starter/client";
    setPackageJsonScript(
      outputDir,
      "dev:desktop",
      `concurrently -k -n next,electron -c blue,magenta ` +
        `"PORT=${nativeHmr} pnpm --filter ${clientPkgName} dev" ` +
        `"wait-on http://localhost:${nativeHmr} && pnpm electron:compile && ` +
        `ELECTRON_DEV_URL=http://localhost:${nativeHmr} electron electron/main.js"`,
    );
  }
}

/** Rewrite the local-infra identifiers that the starter ships with
 *  literal `starter-*` names so each scaffolded project gets its own
 *  unique MongoDB database name, local S3 bucket name, and E2E
 *  isolation. Without this, two scaffolded projects on one dev
 *  machine would share the same dev S3 bucket / Mongo DB.
 *
 *  Only rewrites the suffixed forms (`starter-dev`, `starter-e2e`,
 *  `starter-assets`) — those are unambiguous local-infra identifiers
 *  tied to the starter's name. Bare `starter` and `@starter/*`
 *  occurrences are left to the package-rename pass in pkg-json.ts and
 *  to `replaceInFile` on package.json.
 *
 *  Targets:
 *    · docker-compose.dev.yml                 (S3_BUCKET)
 *    · packages/server/.env.development        (MONGODB_URI, S3_BUCKET_NAME, S3_PUBLIC_URL)
 *    · packages/server/.env.example            (same three keys)
 *    · playwright.config.ts                    (E2E DB + bucket + public URL)
 *    · packages/server/src/config/env.ts       (Zod fallback default for S3_BUCKET_NAME)
 *
 *  Idempotent — after the first run the literal `starter-` prefix is
 *  gone, so re-runs (e.g. through `hatchkit update`) are no-ops. */
export function applyProjectName(outputDir: string, projectName: string): void {
  const replacements: Array<[from: string, to: string]> = [
    ["starter-dev", `${projectName}-dev`],
    ["starter-e2e", `${projectName}-e2e`],
    ["starter-assets", `${projectName}-assets`],
  ];
  const targets = [
    "docker-compose.dev.yml",
    "packages/server/.env.development",
    "packages/server/.env.example",
    "playwright.config.ts",
    "packages/server/src/config/env.ts",
  ];
  for (const rel of targets) {
    const path = join(outputDir, rel);
    rewriteFile(path, (content) => {
      let out = content;
      for (const [from, to] of replacements) out = out.replaceAll(from, to);
      return out;
    });
  }
}
