/*
 * cli/src/features/deploy-recovery/index.ts — write the client-side
 * answer to "this tab is older than the deploy it is talking to" into a
 * project.
 *
 * The deploy pipeline already proves that the thing running is the thing
 * it built (scaffold/deploy-verification.ts): both images carry their
 * commit, the client publishes it as a build-info file, and the deploy
 * job polls both until they agree. Everything here is the other end of
 * that same fact — the browser tab that was open the whole time, still
 * running the previous bundle, about to ask for a chunk the new image
 * does not have.
 *
 * This module is the thin write-through. Every decision it acts on lives
 * in ./policy.ts, every file it writes comes out of ./client-sources.ts,
 * and every config it retrofits goes through ./serving.ts.
 *
 * It writes NOTHING directly: every mutation goes through `ctx.ledger`,
 * so `--dry-run` and the idempotency invariant are structural here
 * rather than remembered. Which primitive each file gets is the whole
 * design decision in this file — see the comment on
 * {@link applyDeployRecovery} and `docs/feature-authoring.md` →
 * "Editing a file the user also edits".
 */

import {
  type OperationalContext,
  type OperationalOutcome,
  applied,
  hasClientHalf,
  skipped,
} from "../operational-context.js";
import {
  buildInfoWriterSource,
  chunkReloadSource,
  clientHostSource,
  clientPolicySource,
  componentSource,
  errorBoundarySource,
  globalErrorBoundarySource,
  versionCheckSource,
} from "./client-sources.js";
import type { ClientSourceOptions } from "./client-sources.js";
import { applyLayoutMount } from "./layout.js";
import {
  CHUNK_RELOAD_STORAGE_KEY,
  DEFAULT_CHUNK_RELOAD_GUARD_MS,
  DEFAULT_VERSION_CHECK_INTERVAL_MS,
} from "./policy.js";
import { nginxNoCacheLocation, upgradeNextConfig, upgradeNginxConf } from "./serving.js";

/** Served path of the build-info file. The same file the image build
 *  stamps and the deploy gate polls — one fact, one file. Inventing a
 *  second one is how a project ends up with two answers to "which build
 *  is this?" and no rule for which one wins. */
export const BUILD_INFO_PATH = "/version.json";

/** Build-time variable the bundle reads its own commit from. Must be a
 *  name the bundler inlines, which is why it is not `COMMIT_SHA`. */
export const BUILD_COMMIT_ENV_VAR = "NEXT_PUBLIC_BUILD_COMMIT";

/** Where the local writer script lands, relative to the project root. */
export const BUILD_INFO_WRITER_REL_PATH = "scripts/write-version-json.mjs";

/** The call that makes an error boundary part of this feature. A
 *  boundary the project already had counts as wired when it contains
 *  this, whatever the rest of the file looks like — see
 *  {@link applyDeployRecovery}. */
const CHUNK_RELOAD_CALL = "reloadOnceForChunkError";

/** Client package directories to look in, in order, when the project
 *  does not have one at the root. Anything else has to be laid out like
 *  one of these — guessing deeper than this would start writing React
 *  files into a server package. */
const CLIENT_DIR_CANDIDATES = ["packages/client", "apps/web", "packages/web", "client", "web"];

/** Join project-relative path segments. Forward slashes throughout and
 *  no `.` segments, because these are ledger keys rather than host
 *  paths: the ledger reports them back to the user verbatim. */
function relJoin(...parts: string[]): string {
  return parts.filter((part) => part !== "" && part !== ".").join("/");
}

/** Tell whether a project-relative path is there, through the ledger
 *  rather than `node:fs` — one object decides what this module may see
 *  and what it may change. */
type Exists = (rel: string) => boolean;

/** Resolve the client package directory. Falls back to the project root,
 *  which is right for a single-package static site. */
export function resolveClientDir(exists: Exists): string {
  for (const candidate of CLIENT_DIR_CANDIDATES) {
    if (exists(`${candidate}/package.json`)) return candidate;
  }
  return ".";
}

/**
 * Where the client's source tree starts, relative to the client package.
 *
 * Next.js accepts `app/` and `src/app/` and refuses to build with both,
 * so an existing `app/` decides it. With neither, `src/` is the shape the
 * starter uses.
 */
export function resolveSourceRoot(exists: Exists, clientDirRel: string): string {
  if (exists(relJoin(clientDirRel, "app"))) return ".";
  return "src";
}

/**
 * Apply the whole module.
 *
 * Three kinds of write, and the difference between them is the point:
 *
 *   · The four modules under `lib/deploy-recovery/`, the component and
 *     the build-info writer script are OWNED. This module generates them
 *     and regenerates them whenever the policy changes, which is exactly
 *     what `writeIfChanged` is for, and each carries a "Generated by
 *     hatchkit" header so it says it is owned. They used to be skipped
 *     forever after the first run; that meant a project could never
 *     receive a fix to the chunk detector it is the entire point of.
 *   · The error boundaries are NOT owned. `app/error.tsx` and
 *     `app/global-error.tsx` are ordinary Next.js files and a project
 *     may well have written its own; silently replacing somebody's error
 *     screen is a worse bug than the stale tab this closes. They are
 *     written when absent, left alone when present, and reported as a
 *     note when the one that is there does not call
 *     `reloadOnceForChunkError` — which is the only part of them this
 *     module actually needs. `ctx.force` overrides that, and is the
 *     only thing this module reads it for.
 *   · Everything else EDITS a file the project owns: the root layout,
 *     the Next config, the nginx config. Those go through `ledger.edit`
 *     with the transforms from ./layout.ts and ./serving.ts. Each is a
 *     fixed point and each returns its input unchanged when its anchor
 *     is missing, so a hand-rolled config is left alone with a note
 *     rather than half-rewritten.
 *
 * The generated build-info file is added to `.gitignore` with
 * `ensureLine`, rather than asked for in a note. It is written per build
 * — by the script locally and by the client Dockerfile in CI — so a
 * committed copy is a stale answer to the one question this feature
 * asks.
 */
export function applyDeployRecovery(ctx: OperationalContext): OperationalOutcome {
  if (!hasClientHalf(ctx.project.surfaces)) {
    return skipped("a backend project has no browser tab that can outlive a deploy");
  }

  const { ledger } = ctx;
  const exists: Exists = (rel) => ledger.exists(rel);
  const notes: string[] = [];

  const clientDirRel = resolveClientDir(exists);
  const sourceRootRel = relJoin(clientDirRel, resolveSourceRoot(exists, clientDirRel));

  const sourceOptions: ClientSourceOptions = {
    buildInfoPath: BUILD_INFO_PATH,
    commitEnvVar: BUILD_COMMIT_ENV_VAR,
    intervalMs: DEFAULT_VERSION_CHECK_INTERVAL_MS,
    chunkGuardMs: DEFAULT_CHUNK_RELOAD_GUARD_MS,
    chunkGuardKey: CHUNK_RELOAD_STORAGE_KEY,
  };

  const libDir = relJoin(sourceRootRel, "lib", "deploy-recovery");
  ledger.writeIfChanged(relJoin(libDir, "policy.ts"), clientPolicySource(sourceOptions));
  ledger.writeIfChanged(relJoin(libDir, "host.ts"), clientHostSource(sourceOptions));
  ledger.writeIfChanged(relJoin(libDir, "version-check.ts"), versionCheckSource(sourceOptions));
  ledger.writeIfChanged(relJoin(libDir, "chunk-reload.ts"), chunkReloadSource(sourceOptions));
  ledger.writeIfChanged(
    relJoin(sourceRootRel, "components", "deploy-recovery.tsx"),
    componentSource(sourceOptions),
  );

  // Error boundaries only where there is a router to attach them to.
  // Writing app/error.tsx into a project with no app directory creates a
  // file nothing ever renders, and the guard it carries would look wired
  // up without being wired up at all.
  const appDirRel = relJoin(sourceRootRel, "app");
  if (exists(appDirRel)) {
    ensureErrorBoundary(
      ctx,
      relJoin(appDirRel, "error.tsx"),
      errorBoundarySource(sourceOptions),
      notes,
    );
    ensureErrorBoundary(
      ctx,
      relJoin(appDirRel, "global-error.tsx"),
      globalErrorBoundarySource(sourceOptions),
      notes,
    );
  } else {
    notes.push(
      "No app router directory found — call reloadOnceForChunkError() from this project's error boundary, or a chunk failure it catches never recovers",
    );
  }

  const publicTarget = relJoin(clientDirRel, `public${BUILD_INFO_PATH}`);
  ledger.writeIfChanged(
    BUILD_INFO_WRITER_REL_PATH,
    buildInfoWriterSource({ defaultTarget: publicTarget }),
  );
  // Created when the project has no ignore file of its own: this entry
  // has to exist somewhere, and a generated per-build file committed to
  // the repo is the one outcome that makes the build-info answer lie.
  ledger.ensureLine(".gitignore", publicTarget, { create: true });

  applyServingNoCache(ctx, clientDirRel, notes);

  // Mount the component. Everything above is inert until this happens,
  // and a note asking somebody to do it is the quietest way for the
  // whole feature never to run — see features/deploy-recovery/layout.ts.
  notes.push(applyLayoutMount({ ledger, sourceRootRel }));

  return applied(notes);
}

/**
 * Write an error boundary, unless the project has one of its own.
 *
 * A boundary that is already exactly what this module generates is
 * written through `writeIfChanged` so the ledger records it as
 * `unchanged` rather than saying nothing at all. One that differs is
 * left alone: it is either a boundary somebody wrote, or this one with
 * its markup extended, and both are theirs. The note goes out only when
 * the existing file does not call `reloadOnceForChunkError`, because
 * that call is the one thing the feature needs from it — a boundary that
 * already has it, however it got there, is wired.
 */
function ensureErrorBoundary(
  ctx: OperationalContext,
  rel: string,
  content: string,
  notes: string[],
): void {
  const existing = ctx.ledger.read(rel);
  if (existing === undefined || existing === content || ctx.force === true) {
    ctx.ledger.writeIfChanged(rel, content);
    return;
  }
  if (existing.includes(CHUNK_RELOAD_CALL)) return;
  notes.push(
    `${rel} already exists and never calls ${CHUNK_RELOAD_CALL}() — add the isChunkLoadFailure effect from lib/deploy-recovery to it, or a chunk failure it catches never recovers`,
  );
}

/**
 * Retrofit whichever config serves the bundle, so the build-info file
 * goes out uncached.
 *
 * Both transforms are fixed points and both return their input unchanged
 * when their anchor is missing, which is what makes `ledger.edit` the
 * right primitive: a config this module does not recognise is reported
 * in a note and left exactly as it is.
 *
 * The self-host proxy config is deliberately left alone: it is owned
 * elsewhere and carries the same rule already.
 */
function applyServingNoCache(ctx: OperationalContext, clientDirRel: string, notes: string[]): void {
  const nextOptions = { buildInfoPath: BUILD_INFO_PATH, commitEnvVar: BUILD_COMMIT_ENV_VAR };
  const nextConfigRel = ["next.config.ts", "next.config.mjs", "next.config.js"]
    .map((name) => relJoin(clientDirRel, name))
    .find((rel) => ctx.ledger.exists(rel));

  if (nextConfigRel !== undefined) {
    const before = ctx.ledger.read(nextConfigRel);
    const upgrade = upgradeNextConfig(before ?? "", nextOptions);
    ctx.ledger.edit(nextConfigRel, (content) => upgradeNextConfig(content, nextOptions).content);
    notes.push(...upgrade.notes);
    if (upgrade.changed || upgrade.noCacheRule) return;
  }

  const nginxConfigRel = [relJoin(clientDirRel, "nginx.conf"), "nginx.conf"].find((rel) =>
    ctx.ledger.exists(rel),
  );
  if (nginxConfigRel !== undefined) {
    const before = ctx.ledger.read(nginxConfigRel);
    const upgrade = upgradeNginxConf(before ?? "", BUILD_INFO_PATH);
    ctx.ledger.edit(
      nginxConfigRel,
      (content) => upgradeNginxConf(content, BUILD_INFO_PATH).content,
    );
    notes.push(...upgrade.notes);
    return;
  }

  if (nextConfigRel === undefined) {
    notes.push(
      `Serve ${BUILD_INFO_PATH} with no caching. For the nginx client image, add to its server block:\n${nginxNoCacheLocation(BUILD_INFO_PATH)}`,
    );
  }
}
