version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/mcp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/dev-plugin-next"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/dev-plugin-vite"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/dev-shared"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/starter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"
