/*
 * cli/src/features/raycast/index.ts — the `raycast` feature.
 *
 * It adds `packages/raycast`: a macOS launcher extension with five commands,
 * bound to the shared client core rather than reimplementing any of it, and
 * two build scripts that produce and verify a standalone, store-publishable
 * copy of the package.
 *
 * ============================================================
 * WHAT IT IS, AND WHAT IT DELIBERATELY IS NOT
 * ============================================================
 *
 * It is a UI SHELL. The offline queue, the optimistic overlay, the read
 * cache, the drain-before-read rule, the queue-behind-writes rule, the replay
 * classifier and the per-origin capability cache are all `@starter/core`'s,
 * and the package binds Raycast's `LocalStorage` to the kit's one storage seam
 * and calls into it. A second copy of any of those would fork this surface's
 * behaviour from every other client's — silently, because a queue that
 * replays slightly differently still replays.
 *
 * It is NOT a second pairing mechanism. Auth is the shared device grant —
 * better-auth's RFC 8628 plus `bearer()` — with the token in Raycast's
 * encrypted store and `clientId` read from `identifiers.clientIds.raycast`.
 *
 * ============================================================
 * THE PREREQUISITE, AND WHY IT IS NOT AN IMPORT
 * ============================================================
 *
 * `requires: ["client-core"]` although the launcher never imports
 * `@starter/core`: it imports `src/vendor/`, a generated byte-for-byte copy.
 * The Raycast Store builds an extension ALONE with a plain `npm install`,
 * where a `workspace:*` dependency cannot resolve at all, so a workspace
 * import would be a package that builds here and nowhere else.
 *
 * The prerequisite is still real and still enforced, because the GENERATOR
 * reads `packages/core/src` and `packages/shared/src`. Without them
 * `pnpm run vendor:raycast` has nothing to copy, and the extension's own test
 * run fails on the first check.
 *
 * ============================================================
 * WHY THE WORKSPACE PACKAGE IS NOT `@<scope>/raycast`
 * ============================================================
 *
 * Raycast reads `package.json`'s `name` as the extension's store slug, which
 * must be a bare lowercase identifier — and pnpm reads the same field as the
 * workspace package name. One field, two readers, so the workspace name is the
 * store slug. That slug and the publisher handle together key Raycast's
 * encrypted per-extension store, which is why both are frozen at scaffold
 * time and why the package's PUBLISHING.md says what changing one costs.
 */

import type { Surface } from "../../prompts.js";
import { clientCoreFeature } from "../client-core/index.js";
import {
  type FeatureContext,
  type FeatureId,
  type FeaturePlanContext,
  registerFeature,
} from "../contract.js";
import { applyRaycast, raycastPlannedFiles } from "./apply.js";

export * from "./types.js";
export { applyRaycast, raycastPlannedFiles, raycastResidue } from "./apply.js";
export {
  findRaycastIdentifierLiterals,
  raycastNamesFrom,
  renameRaycastIdentifiers,
  renameRaycastTree,
  type RaycastNames,
} from "./rename.js";
export { stripRaycast, stripRaycastScripts } from "./strip.js";

/** What the feature needs, in the words the CLI shows people. */
export const RAYCAST_PREREQUISITE =
  "the shared client core (packages/core + packages/shared) and a server runtime";

/**
 * Null when `surfaces` can carry the launcher, otherwise the sentence to show.
 *
 * Shared by the create flow, the non-interactive validator and
 * `hatchkit update`, so the three cannot answer differently.
 */
export function raycastPrerequisiteProblem(surfaces: Surface): string | null {
  if (surfaces === "static") {
    return "The `raycast` feature needs a server runtime: the launcher has no cookie jar, so it signs in through the server's device flow and carries a bearer token. A `static` project has no server. Pick `fullstack` or `split`.";
  }
  if (surfaces === "backend") {
    return "The `raycast` feature needs a web app: a pairing code is approved on one, and every command that cannot do something opens it. A `backend` project ships no client. Pick `fullstack` or `split`.";
  }
  return null;
}

const RAYCAST_ID: FeatureId = "raycast";

export const raycastFeature = registerFeature({
  /**
   * Annotated through `FeatureId`, never asserted into it. The annotation is
   * what proves the `Feature` union names this id; an `as FeatureId` would
   * survive a rename or a typo and the only symptom would be a feature that
   * is never offered.
   */
  id: RAYCAST_ID,
  title: "Raycast launcher extension",
  summary:
    "Five launcher commands over the shared client core, with a store-publishable export and a vendored copy of the kit.",
  // Referenced through the definition rather than by string, so importing
  // this feature registers the one it needs — an id the registry has never
  // seen reads as "unknown feature", not as a prerequisite.
  requires: [clientCoreFeature.id],
  // A pairing code is approved on a web page and the bearer token comes from
  // a server's device flow, so neither half can be missing.
  surfaces: ["fullstack", "split"],
  // Everything it writes is its own directory plus add-only root scripts, so
  // `update` can add it to a project that has been running for months.
  addableAfterScaffold: true,
  apply(ctx: FeatureContext): void {
    ctx.log("  raycast: launcher extension over the shared client kit");
    for (const line of applyRaycast(ctx)) ctx.log(`  ${line}`);
    for (const conflict of ctx.ledger.conflicts()) {
      ctx.log(`  raycast: ${conflict.file} — ${conflict.detail ?? "not applied"}`);
    }
  },
  plannedFiles(ctx: FeaturePlanContext): readonly string[] {
    return raycastPlannedFiles(ctx);
  },
});
