#!/usr/bin/env bash
# Start and stop one server stack for a compatibility run.
#
#   scripts/compat-server.sh up     start it, wait for it, print COMPAT_API_URL=
#   scripts/compat-server.sh down   stop it and remove its volumes
#
# `.github/workflows/compat.yml` runs this twice per pull request, once per
# direction, with a different image each time. Everything that differs between
# the two arrives as an environment variable, so this script has no idea which
# direction it is serving:
#
#   COMPAT_COMPOSE_FILE   compose file to start (required)
#   COMPAT_SERVER_IMAGE   image to run the server from (required)
#   COMPAT_PROJECT        compose project name; its own volumes and database
#   COMPAT_PULL           always | anonymous | never  (default: anonymous)
#   COMPAT_SERVICE        service holding the server  (default: server)
#   COMPAT_PORT           port the server listens on  (default: 3000)
#   COMPAT_HEALTH_PATH    path that answers once it is up (default: /api/health)
#   COMPAT_TIMEOUT        seconds to wait for that answer (default: 180)
#   COMPAT_LOGS           non-empty on `down` dumps the stack's logs first
#
# Each run gets its own compose project, so two directions can run at once
# without sharing a database. Nothing here pushes, publishes, or writes
# outside the stack it started.
#
# The workflow invokes this as `bash scripts/compat-server.sh`, so it works
# from a fresh clone whether or not the exec bit survived.
#
# Generated by `hatchkit update` from .hatchkit-release.json. Hand edits are
# lost on the next run.
set -euo pipefail

COMPOSE_FILE="${COMPAT_COMPOSE_FILE:?COMPAT_COMPOSE_FILE is required}"
PROJECT="${COMPAT_PROJECT:-compat}"
SERVICE="${COMPAT_SERVICE:-server}"
PORT="${COMPAT_PORT:-3000}"
HEALTH_PATH="${COMPAT_HEALTH_PATH:-/api/health}"
TIMEOUT="${COMPAT_TIMEOUT:-180}"
PULL="${COMPAT_PULL:-anonymous}"

compose() {
  docker compose --file "$COMPOSE_FILE" --project-name "$PROJECT" "$@"
}

case "${1:-}" in
  up)
    IMAGE="${COMPAT_SERVER_IMAGE:?COMPAT_SERVER_IMAGE is required}"

    # A self-hoster with no registry login pulls anonymously. Testing the
    # pull the way they do it is part of testing the release.
    if [ "$PULL" = "anonymous" ]; then
      docker logout ghcr.io >/dev/null 2>&1 || true
      docker pull "$IMAGE"
    elif [ "$PULL" = "always" ]; then
      docker pull "$IMAGE"
    fi

    # The compose file reads the image from its own version variable; both
    # spellings are set so a project need not use one particular name.
    export COMPAT_SERVER_IMAGE="$IMAGE"
    export SERVER_IMAGE="$IMAGE"

    compose up --detach --wait --no-build "$SERVICE" 2>/dev/null ||
      compose up --detach "$SERVICE"

    # The port compose actually published: the fixed one is already taken
    # when the other direction is running on the same machine.
    published="$(compose port "$SERVICE" "$PORT" 2>/dev/null | tail -n 1 || true)"
    host_port="${published##*:}"
    [ -n "$host_port" ] || host_port="$PORT"
    url="http://127.0.0.1:${host_port}"

    printf 'Waiting up to %ss for %s%s\n' "$TIMEOUT" "$url" "$HEALTH_PATH" >&2
    deadline=$(( $(date +%s) + TIMEOUT ))
    until curl --fail --silent --show-error --output /dev/null "${url}${HEALTH_PATH}"; do
      if [ "$(date +%s)" -ge "$deadline" ]; then
        echo "compat-server: ${url}${HEALTH_PATH} did not answer within ${TIMEOUT}s" >&2
        compose ps >&2 || true
        compose logs --no-color --tail 200 >&2 || true
        exit 1
      fi
      sleep 2
    done

    # The workflow greps this line into GITHUB_ENV, so it goes to stdout on
    # its own while every progress message above went to stderr.
    echo "COMPAT_API_URL=${url}"
    ;;

  down)
    # Only on a failure: the logs are the evidence, and printing them on a
    # green run buries the one that matters.
    if [ -n "${COMPAT_LOGS:-}" ]; then
      compose logs --no-color --tail 400 || true
    fi
    compose down --volumes --remove-orphans || true
    ;;

  *)
    echo "usage: scripts/compat-server.sh up|down" >&2
    exit 2
    ;;
esac
