---
sidebar_position: 5
description: Every REST endpoint under /api/v1, the scope it requires, and where its parameters go.
---

{/* Generated by src/api/v1/emit-openapi.ts — do not edit by hand. */}

# API reference

Every route below is mounted from one array, `API_ROUTES` in
`src/api/v1/routes-table.ts`, and this page and
[the OpenAPI document](pathname:///openapi.json) are both generated from it. A route
cannot exist here and not in the server, or in the server and not here.

All paths are relative to `/api/v1`. Every route but `/openapi.json` needs
`Authorization: Bearer sk_…`. **Parameters** says where a route's input goes:
`query` for a GET filter, `body` for JSON, `path` for the id in the URL. Full
field-level shapes live in the OpenAPI document.

## Items

| Method | Path | Scope | Parameters | What it does |
| --- | --- | --- | --- | --- |
| `GET` | `/items` | `items:read` | query | List items, newest first. Excludes other members' items without `items:view-others`. |
| `GET` | `/items/:id` | `items:read` | path | One item. 404 for an id in another tenant, never 403. |
| `POST` | `/items` | `items:write` | body | Create an item, owned by the member this token acts as. |
| `PATCH` | `/items/:id` | `items:write` | body | Edit an item. 403 for another member's item without `items:write-others`. |
| `DELETE` | `/items/:id` | `items:write` | path | Delete an item. Same refusals as the edit. |

## Webhooks

| Method | Path | Scope | Parameters | What it does |
| --- | --- | --- | --- | --- |
| `GET` | `/webhooks` | `webhooks:read` | query | List this tenant's webhook subscriptions. Secrets are never echoed. |
| `POST` | `/webhooks` | `webhooks:write` | body | Create a subscription. The signing secret is returned once, here, and never again. |
| `GET` | `/webhooks/:id/deliveries` | `webhooks:read` | query | Recent delivery attempts for one subscription, newest first. |
| `DELETE` | `/webhooks/:id` | `webhooks:write` | path | Delete a subscription. Queued deliveries for it stop at their next attempt. |

## Meta

| Method | Path | Scope | Parameters | What it does |
| --- | --- | --- | --- | --- |
| `GET` | `/openapi.json` | none — public | — | This API's OpenAPI 3.1 document. |
| `GET` | `/me` | any valid token | — | This token's own tenant, scopes and effective permissions. |

## The document itself

- [`openapi.json`](pathname:///openapi.json) — the committed copy this site serves.
- `GET /api/v1/openapi.json` — the live one, unauthenticated, generated per request
  from the running server's own route table. Point a client generator at it.
