/*
 * cli/src/features/env-agreement/doc.ts — the project-facing write-up of
 * both rules, generated from the same list the check reads.
 *
 * Why generated rather than a template file in `starter/`: a hand-written
 * page listing "the four places that must agree" is correct on the day it
 * is written and wrong the first time someone adds a fifth client. The
 * page below is rendered from {@link ORIGIN_SITES}, so a site added to
 * that list appears here and in `hatchkit doctor` together, and the
 * document cannot claim a number the check does not use.
 */

import type { OperationalProject } from "../operational-context.js";
import { defaultApiOrigin } from "../operational-context.js";
import type { OriginSite } from "./sites.js";
import { ORIGIN_SITES, siteLocation } from "./sites.js";

/** Where the generated page goes, relative to the project root. */
export const ENV_SOURCES_DOC_REL_PATH = "docs/env-sources.md";

/** Render `docs/env-sources.md` for a project.
 *
 *  `sites` exists so the test can prove the derivation — it renders the
 *  page with one extra site and asserts the page grew. Every real caller
 *  wants the default. */
export function renderEnvSourcesDoc(
  project: OperationalProject,
  sites: readonly OriginSite[] = ORIGIN_SITES,
): string {
  const expected = defaultApiOrigin(project.domain, project.topology);
  const applicable = sites.filter((s) => s.required(project));
  const optional = sites.filter((s) => !s.required(project));

  const lines: string[] = [
    "# Where this project's configuration lives",
    "",
    "Generated by `hatchkit`. Two rules, both of which fail silently when",
    "broken: nothing errors at the moment of the mistake, and the symptom",
    "arrives later and somewhere else.",
    "",
    "## 1. The default API origin",
    "",
    `This deployment serves its API at **${expected}**.`,
    "",
    "Every client carries its own copy of that origin, and each copy is",
    "baked in at a different moment — image build, release build, store",
    "review. They drift apart without anything failing. Each one is a",
    "DEFAULT: a person can point their own copy elsewhere at runtime,",
    "which is exactly why a wrong default goes unnoticed by the people",
    "who would have caught it.",
    "",
    `The places this project carries it (${applicable.length}):`,
    "",
  ];

  for (const site of applicable) {
    lines.push(`- **${site.label}** — \`${siteLocation(site)}\``);
    lines.push(`  - Wrong value: ${site.symptom}.`);
    // A site hatchkit deliberately does not fill says so here, next to
    // the consequence, rather than only in the output of the one command
    // that wrote this page.
    const manual = site.manualStep?.(expected);
    if (manual) lines.push(`  - You set this: ${manual}.`);
  }

  if (optional.length > 0) {
    lines.push(
      "",
      "Not part of this project today. If one is added, it joins the list",
      "above and has to carry the same origin:",
      "",
    );
    for (const site of optional) {
      lines.push(`- ${site.label} — \`${siteLocation(site)}\``);
    }
  }

  lines.push(
    "",
    "`hatchkit doctor` compares all of them against the deployment's own",
    "domain. It derives the expected origin from the manifest rather than",
    "trusting any one site, so a project whose server holds the wrong",
    "value is reported rather than treated as the truth.",
    "",
    "### Some places hold no default on purpose",
    "",
    "The release workflows do not carry a literal origin hatchkit wrote.",
    "The mobile one reads a repository secret and its plan job fails the",
    "run when that secret is empty. The desktop one reads a repository",
    "variable, and its build fails before it starts when that variable is",
    "empty.",
    "",
    "Both refuse to guess, because the value is baked into an artifact a",
    "redeploy cannot correct. `hatchkit doctor` reports those places as",
    "`enforced` rather than as a failure: nothing is broken, and the value",
    "is a one-time step listed with the site above.",
    "",
    "## 2. Production environment lives in the platform's environment fields",
    "",
    "Not in a file in this repository.",
    "",
    "The encrypted `.env.production` mechanism this template inherits only",
    "works when the ciphertext is inside the running image. It is not: the",
    "file is excluded from the repository, and the runtime stage of the",
    "server Dockerfile copies `dist`, `package.json` and `node_modules` and",
    "nothing else. A production private key on the platform therefore has",
    "nothing to open.",
    "",
    "So a value set in that file deploys green and leaves the server on the",
    "old values, with nothing in the diff to point at. Keep the file for",
    "running the production build locally; treat the platform's environment",
    "fields as the source of truth.",
    "",
    "### A platform field only reaches a container the compose file names",
    "",
    "Those fields are interpolation variables FOR THE COMPOSE FILE. A",
    "variable set on the platform against a compose file that never writes",
    "`${VAR}` reaches no container — it sits in the dashboard looking set.",
    "The reverse fails just as quietly: a `${VAR}` with no default that",
    "nobody sets interpolates to an empty string and the container starts",
    "anyway.",
    "",
    "To add a value: write `${NEW_VAR}` into the compose file's",
    "`environment:` block first, then set the field on the platform, then",
    "redeploy so the container is recreated with the new interpolation.",
    "",
  );

  return `${lines.join("\n")}`;
}
