/*
 * cli/src/features/docs-in-client/render.ts — the artefacts this feature
 * writes into a project.
 *
 * Four of them, and each one exists because of a failure that is invisible
 * from the outside:
 *
 *   1. `scripts/docs/build-into-client.mjs` — builds the docs with the
 *      published base path, copies them into the client's build output and
 *      refuses to finish if the result would not be indexed. Rendered from
 *      `rules.ts`, so its checks cannot drift from the ones the tests drive.
 *   2. `packages/client/src/app/robots.ts` — the domain's ONE robots file,
 *      naming both sitemaps. A second one under the docs path is never read
 *      by anything, which is why the audit fails the build over it.
 *   3. `packages/client/src/lib/docs-links.ts` — absolute addresses for the
 *      marketing pages, with plain anchors rather than the router's
 *      client-side navigation.
 *   4. `.github/workflows/docs-verify.yml` — the same check on a pull
 *      request, for a project whose own workflow the retrofit could not
 *      match.
 *
 * Every generated file carries the reason it is shaped that way, in its own
 * comments. The reasons are the point: each of these looks like pointless
 * ceremony to a reader who has not seen the failure, and a reader who
 * undoes one gets a site that builds, deploys, serves every page — and is
 * never indexed.
 */

import type { DocsLayout } from "./paths.js";
import { CLIENT_PACKAGE_DIR, DOCS_SCRIPT_REL_PATH } from "./paths.js";
import { renderRulesArray } from "./rules.js";

/**
 * The copy-and-audit step the client image runs after the client build.
 *
 * Plain JavaScript with no dependencies: it runs inside a Docker build
 * stage, where there is no TypeScript toolchain, and in CI before anything
 * has been compiled. Its audit is exported and its entry point is guarded,
 * so the test suite can import it and run the same rules the generated
 * project will run.
 */
export function renderDocsBuildScript(layout: DocsLayout): string {
  const { basePath, docsPackage, publishedPrefix } = layout;
  return `#!/usr/bin/env node
/**
 * Builds the docs site and puts it inside the web client's build output, so
 * the client image serves the docs at ${publishedPrefix}.
 *
 *   node ${DOCS_SCRIPT_REL_PATH}            build the docs, copy them, audit the copy
 *   node ${DOCS_SCRIPT_REL_PATH} --check    build the docs and audit them, copy nothing
 *
 * Run AFTER the client build, never as part of it. See the loud comment in
 * ${CLIENT_PACKAGE_DIR}/Dockerfile: the client's build output is also written by the
 * end-to-end suite and by the native shells' builds, and only the web image
 * should carry the docs.
 *
 * A folder of the main domain rather than a host of its own, because one
 * domain keeps all the search authority in one place. And a folder of THIS
 * image rather than a second application or a proxy path, because it then
 * needs no routing at all: the proxy merges the site blocks of two
 * applications that claim the same host, and a proxy path strips the prefix
 * that a "${basePath}" build needs to keep.
 *
 * The costs are deliberate and small. A docs-only change rebuilds and
 * redeploys the client image, which never restarts the server. And the image
 * build installs the docs site's dependencies.
 *
 * What it checks for, after building, is the class of failure that looks
 * exactly like success: a page that asks search engines not to index it, a
 * canonical link to an address the site is not served from, a sitemap
 * pointing somewhere else, a robots file that nothing will ever read. Any of
 * them and the build fails here.
 *
 * Generated by hatchkit (feature: docs-in-client), which owns this file and
 * rewrites it on every \`hatchkit update\`. Change it at the source instead.
 */

import { spawnSync } from "node:child_process";
import { cpSync, existsSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/** The repository root, from this file's own location. */
export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/** The workspace package holding the docs site, and where its build lands. */
export const DOCS_PACKAGE = ${JSON.stringify(docsPackage)};
export const DOCS_BUILD_DIR = resolve(REPO_ROOT, ${JSON.stringify(`${docsPackage}/build`)});

/**
 * Where the docs are published. A LITERAL, and indexing is always on.
 *
 * Not a variable with a fallback, which is the shape that fails: a docs
 * config that reads its address from the environment falls back to a
 * placeholder, and a placeholder address is paired with noindex, no sitemap
 * and a "Disallow: /" robots file — correctly, because a placeholder must
 * not be indexed. Forget the variable in one build environment and the
 * shipped site carries all three, with nothing failing anywhere.
 *
 * These two must match \`url\` + \`baseUrl\` in the docs site's own config,
 * which must also spell them as literals. The audit below is what enforces
 * it: a config that disagrees produces canonical links and sitemap entries
 * outside this prefix, and the build stops.
 */
export const PUBLISHED_PREFIX = ${JSON.stringify(publishedPrefix)};
export const DOCS_BASE_PATH = ${JSON.stringify(basePath)};

/**
 * Where the client's build output is, in the order to look.
 *
 * A statically exported client writes \`out/\`, and that is what the image
 * serves. A server-rendered client serves \`public/\` verbatim, and its
 * runtime stage copies that directory, so writing the docs there after the
 * build puts them in the image just the same.
 */
const CLIENT_OUTPUT_CANDIDATES = [
  ${JSON.stringify(`${CLIENT_PACKAGE_DIR}/out`)},
  ${JSON.stringify(`${CLIENT_PACKAGE_DIR}/public`)},
];

function clientOutputDir() {
  for (const candidate of CLIENT_OUTPUT_CANDIDATES) {
    const dir = resolve(REPO_ROOT, candidate);
    if (existsSync(dir)) return dir;
  }
  console.error(
    "[docs] No client build output found (" + CLIENT_OUTPUT_CANDIDATES.join(", ") + ")." +
      " Build the client first, or pass --check to audit the docs without copying them.",
  );
  process.exit(1);
}

/** Extensions worth reading. Everything a rule looks at is text; an image or
 *  a font is skipped rather than read into memory and matched against. A file
 *  with no extension of its own (\`_headers\`, \`.htaccess\`) counts as text,
 *  because that is the shape a headers file takes. */
const TEXT_EXTENSIONS = [".html", ".xml", ".txt", ".json", ".toml", ".md", ".webmanifest"];

function isTextPath(path) {
  const base = path.slice(path.lastIndexOf("/") + 1);
  if (!base.slice(1).includes(".")) return true;
  return TEXT_EXTENSIONS.some((ext) => base.endsWith(ext));
}

/** Every text file below \`dir\`, as { relative POSIX path: contents }. */
export function readDocsTree(dir) {
  const files = {};
  const walk = (current) => {
    for (const name of readdirSync(current).sort()) {
      const path = join(current, name);
      if (statSync(path).isDirectory()) {
        walk(path);
        continue;
      }
      const rel = relative(dir, path).split("\\\\").join("/");
      if (isTextPath(rel)) files[rel] = readFileSync(path, "utf8");
    }
  };
  walk(dir);
  return files;
}

// ---------------------------------------------------------------------------
// The rules.
//
// Generated from one list that the project's own test suite also drives, so
// the checks that run here and the checks that are tested cannot drift apart.
// Edit them at the source (hatchkit: cli/src/features/docs-in-client/rules.ts)
// rather than here.
// ---------------------------------------------------------------------------

${renderRulesArray()}

/** Everything wrong with a built docs tree: { ok, violations }. Each
 *  violation is { code, path, detail } — the code is stable, the prose is
 *  what tells you what to change. */
export function auditDocsTree(dir, publishedPrefix = PUBLISHED_PREFIX) {
  const input = { files: readDocsTree(dir), publishedPrefix };
  const violations = RULES.flatMap((rule) => rule.check(input));
  return { ok: violations.length === 0, violations };
}

function buildDocs() {
  const build = spawnSync("pnpm", ["--filter", DOCS_PACKAGE, "run", "build"], {
    cwd: REPO_ROOT,
    stdio: "inherit",
  });
  if (build.status !== 0) {
    console.error("[docs] The docs site failed to build.");
    process.exit(build.status ?? 1);
  }
}

function run(argv) {
  // --check builds and audits without copying: a pull request wants to know
  // that the docs still build, that every internal link still resolves and
  // that the pages would be indexed, and none of that needs a client build.
  const checkOnly = argv.includes("--check");

  buildDocs();

  let tree = DOCS_BUILD_DIR;
  if (!checkOnly) {
    const target = join(clientOutputDir(), DOCS_BASE_PATH);
    rmSync(target, { recursive: true, force: true });
    cpSync(DOCS_BUILD_DIR, target, { recursive: true });
    tree = target;
  }

  const { ok, violations } = auditDocsTree(tree);
  if (!ok) {
    console.error("[docs] " + relative(REPO_ROOT, tree) + " is not fit to ship:");
    for (const v of violations) {
      console.error("  - " + v.path + " " + v.detail + " [" + v.code + "]");
    }
    process.exit(1);
  }

  if (checkOnly) {
    console.log("[docs] " + relative(REPO_ROOT, tree) + " would be indexed at " + PUBLISHED_PREFIX);
    return;
  }
  console.log("[docs] Copied the docs to " + relative(REPO_ROOT, tree) + ", served at " + PUBLISHED_PREFIX);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  run(process.argv.slice(2));
}
`;
}

/**
 * The domain's one robots file, as a Next.js metadata route.
 *
 * It names both sitemaps because there is only one file to name them in.
 * The docs are a separate build copied into this app's output, and the
 * crawler that reads `https://<domain>/robots.txt` is the only crawler
 * there is — a robots file under the docs path is served, and never
 * requested, which is why the audit fails the build over one.
 */
export function renderRobotsRoute(layout: DocsLayout): string {
  const { basePath, origin } = layout;
  return `import type { MetadataRoute } from "next";

// Written once, at build time, as /robots.txt.
export const dynamic = "force-static";

const SITE_URL = ${JSON.stringify(origin)};

/**
 * The domain's ONE robots file.
 *
 * A crawler reads exactly one robots.txt per host, the one at its root, so
 * this file speaks for the whole domain — including the docs at ${basePath},
 * which are a separate build copied into this app's output
 * (${DOCS_SCRIPT_REL_PATH}).
 *
 * That is why both sitemaps are named here, and why the copy step fails the
 * build if the docs bring a robots file of their own: a second one is
 * served, never requested, and states beliefs about the site that nothing
 * acts on.
 *
 * The docs sitemap carries no last-modified dates. Site generators read
 * those from git history, and an image build context has no repository —
 * worse, a git binary with no repository around it fails the build
 * outright, so the docs config must not reach for one. Missing lastmod
 * costs nothing: crawlers treat it as a hint and refetch anyway.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: [\`\${SITE_URL}/sitemap.xml\`, \`\${SITE_URL}${basePath}sitemap.xml\`],
  };
}
`;
}

/** The sitemaps a generated robots route names, with `SITE_URL` resolved.
 *
 *  A reader, not a renderer: the check that matters about this file is that
 *  it lists BOTH sitemaps, and the test asserts that rather than the file's
 *  bytes. Returns an empty list for a file it cannot parse, which is the
 *  honest answer for a hand-rolled robots route. */
export function sitemapsInRobotsRoute(source: string): string[] {
  const siteUrl = source.match(/const SITE_URL = "([^"]+)"/)?.[1];
  const list = source.match(/sitemap:\s*\[([\s\S]*?)\]/)?.[1];
  if (siteUrl === undefined || list === undefined) return [];
  return [...list.matchAll(/`([^`]+)`|"([^"]+)"/g)]
    .map((m) => m[1] ?? m[2])
    .map((entry) => entry.replace(/\$\{SITE_URL\}/g, siteUrl));
}

/**
 * The marketing pages' addresses for the docs.
 *
 * Absolute, and reached with a plain anchor. Two reasons, both of which bite
 * only in production: another image of this same app can be served on a
 * different domain (a self-hosted instance, a preview host) where no docs
 * are published at all, so a relative link would point at nothing; and the
 * docs path is not a route the app's router knows, so client-side navigation
 * to it either 404s inside the app or is rewritten to a route that does not
 * exist.
 */
export function renderDocsLinksModule(layout: DocsLayout): string {
  const { basePath, publishedPrefix } = layout;
  return `/**
 * Where the docs are, for every page that links to them.
 *
 * ABSOLUTE, and always reached with a plain <a>, never the router's
 * client-side navigation. Two reasons, both of which only bite in
 * production:
 *
 *   1. Another image of this same app is served on other domains — a
 *      self-hosted instance, a preview deployment — and ${basePath} does not
 *      exist there. A relative link would point at nothing; an absolute one
 *      sends the reader to the docs that are actually published.
 *   2. ${basePath} is not a route this app has. It is a separate site copied
 *      into the build output by
 *      ${DOCS_SCRIPT_REL_PATH}, so the router
 *      cannot navigate to it — it has to be a real document request.
 *
 * Keep this in step with PUBLISHED_PREFIX in
 * ${DOCS_SCRIPT_REL_PATH}; the copy step fails the
 * build when the docs are not published here.
 *
 * Generated by hatchkit (feature: docs-in-client), which owns this file and
 * rewrites it on every \`hatchkit update\`. Anything you add here is lost;
 * import DOCS_URL from a module of your own instead.
 */
export const DOCS_URL = ${JSON.stringify(publishedPrefix)};

/** A page inside the docs, e.g. \`docsUrl("self-hosting")\`. */
export function docsUrl(path: string): string {
  return DOCS_URL + path.replace(/^\\/+/, "");
}
`;
}

/** The step that runs the docs check in CI, for insertion into an existing
 *  verify job. Indented for a job's `steps:` list, and carrying its own
 *  reason — a reader who deletes it gets the failure back. */
export function docsVerifyWorkflowStep(): string {
  return `      # The docs are built into the client image on a push to main
      # (${CLIENT_PACKAGE_DIR}/Dockerfile), which is after merge. Building them
      # here too puts a broken internal link, or a page search engines would
      # be told to ignore, in front of the pull request instead of failing
      # the image build once it is too late to be a review comment.
      #
      # --check builds and audits without copying, so this needs no client
      # build and no build arguments.
      - name: Verify the docs build and would be indexed
        run: node ${DOCS_SCRIPT_REL_PATH} --check
`;
}

/** The standalone pull-request check.
 *
 *  Written only for a project whose own deploy workflow the retrofit could
 *  not match — a hand-rolled workflow is safer left alone than half-edited,
 *  but a project with no docs check at all is the failure this feature
 *  exists to prevent. */
export function renderDocsVerifyWorkflow(layout: DocsLayout): string {
  return `name: docs-verify

# The docs are built into the client image on a push to main, which is after
# merge. This job runs the same build and the same checks on the pull
# request, so a broken internal link or a page that would not be indexed
# fails the change rather than the image build.
#
# Standalone because this project's deploy workflow has no verify job to add
# the step to. If one is added later, move this single step into it — one
# checkout and one install is cheaper than two.
#
# Generated by hatchkit (feature: docs-in-client), which owns this file and
# rewrites it on every \`hatchkit update\`.

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      # --check builds the docs (${layout.docsPackage}) and audits the result
      # against ${layout.publishedPrefix} without copying it anywhere, so no
      # client build and no build arguments are needed.
      - run: node ${DOCS_SCRIPT_REL_PATH} --check
`;
}
